/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/puzzles/{puzzleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch a puzzle by id.
         * @description Returns the full puzzle document — every cell and clue. The response
         *     is self-contained: a client with the document can render the grid and
         *     the clue list without further round-trips.
         *
         *     When the optional `X-Session-Id` header is present, clue selection on
         *     cache miss is biased away from clues recently used by the same
         *     session (per ADR-0031 "per-session clue cooldown"). When absent,
         *     clue selection is unaffected — the cooldown machinery is bypassed
         *     end-to-end. Cache hits return the persisted grid as-is regardless of
         *     the header, so the same `puzzleId` always yields the same clues.
         *
         *     When a `__Secure-ws_session` cookie is presented, `hintsRemaining`
         *     reflects the authenticated user's per-puzzle remaining hint count;
         *     anonymous callers receive `hintsRemaining` equal to `hintsAllowed`.
         */
        get: operations["getPuzzle"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/puzzles/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch the daily puzzle for a given date.
         * @description Returns the puzzle of the day for the supplied `date` (or today's
         *     UTC date when omitted). Two callers reach this endpoint: the
         *     Accueil card resolves "today's grid" without holding a UUID, and
         *     the Grille route navigates here when the player picks "Reprendre"
         *     / "Commencer".
         *
         *     The server derives a deterministic UUID v7 from the date and
         *     performs a pure read against the persisted puzzle row populated
         *     ahead of time by the daily-puzzle worker (ADR-0042). Subsequent
         *     hint / validate calls keyed by the returned `id` resolve to the
         *     same canonical grid. When no row exists for the requested date —
         *     worker has not yet run, or persistently failed — the endpoint
         *     returns 404; clients SHOULD retry shortly or surface the
         *     "daily not yet available" message.
         *
         *     `gridNumber` and `difficulty` on the response are populated from
         *     the date (sequence number from a launch-day anchor; difficulty
         *     is `facile` until heuristics land in a follow-up). Other fields
         *     match the `Puzzle` schema. The endpoint ignores any
         *     client-supplied `X-Session-Id` header — the daily bucket is
         *     global by design.
         */
        get: operations["getDailyPuzzle"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/puzzles/daily/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List past + current daily puzzles.
         * @description Returns thin summaries of dailies in the requested range, newest
         *     first. Always excludes future dates; clamps `from` to the launch
         *     anchor (2026-01-01 UTC) and `to` to today UTC. If `from` is later
         *     than `to` after clamping, the response is 200 with an empty `items`
         *     array. Per-user progress is NOT included — clients derive it locally
         *     from the solo-entries store keyed by `id`. The response is bounded
         *     at 100 items.
         */
        get: operations["listDailyPuzzles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/words/sample": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sample random clue→answer pairs for the home teaser.
         * @description Returns a small, count-capped, random sample of `SampleWord`
         *     clue→answer pairs drawn from the resident French corpus, for the
         *     dev-only `/home` teaser mini-game (ADR-0073). The teaser validates
         *     client-side, so this endpoint returns the `answer` in **plaintext**
         *     — a deliberate, ADR-0073-blessed exception to the daily-puzzle
         *     no-leak posture (PR #218): these are a random teaser pool, never the
         *     daily answer key, so exposing them leaks no daily solution.
         *
         *     Inputs are bounded server-side (ADR-0073 §4): `count` is clamped to
         *     the documented maximum, the length range is bounded, and
         *     `minLen ≤ maxLen` is enforced — an inverted or out-of-range request
         *     is rejected with a 400, not silently served.
         */
        get: operations["sampleWords"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/puzzles/{puzzleId}/hints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Spend a hint to reveal the canonical letter at a cell.
         * @description Per-puzzle hint mechanism. The client submits a `(row, column)`
         *     coordinate inside the puzzle; the server returns the canonical
         *     solution letter at that cell and decrements the puzzle's hint
         *     budget. Each answered call costs one hint; once the budget is
         *     exhausted the server responds with 429 and the client UI SHOULD
         *     disable the affordance.
         *
         *     One letter per call, by design: `Puzzle.hintsAllowed` caps total
         *     reveals so unauthenticated clients cannot drain a grid in a single
         *     request. Brute-forcing the full solution still requires
         *     `hintsAllowed` calls and is bounded by edge rate limiting.
         *
         *     Player identity on the wire is the `__Secure-ws_session` cookie
         *     issued by identity-api. The server verifies the cookie against
         *     identity-api's whoami endpoint and keys a per-(puzzle, user) hint
         *     counter on the resolved `userId`. Missing or revoked cookies
         *     produce a 401 `auth-required` response. Coordinates that point at
         *     a non-letter cell (definition or block) or that fall outside the
         *     puzzle bounds produce a 400 `invalid-coord` and do NOT decrement
         *     the budget.
         */
        post: operations["revealCellHint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/puzzles/{puzzleId}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify a filled grid against the canonical solution.
         * @description Compares submitted cells against the server's canonical solution.
         *     Returns whether the grid is solved and, if not, the positions of
         *     mismatched or unfilled cells — never the canonical letter. The
         *     response cannot be used to reconstruct the solution in a single
         *     call; brute-force letter extraction would require
         *     `O(width × height × 26)` legal calls and is mitigated by edge rate
         *     limiting (ops concern, out of scope for this schema).
         *
         *     Stateless: any client holding a `puzzleId` may call. Cleared cells
         *     are absent from the request — do NOT send `letter: null`.
         */
        post: operations["validatePuzzle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Erase server-side data for a session (RGPD Article 17).
         * @description Removes every server-side row attributable to `sessionId`. That
         *     covers `puzzle_hint_usage` always, and `clue_cooldown_session` /
         *     `clue_cooldown` when the clue-cooldown feature is wired
         *     (ADR-0031). Any future table keyed on a `session_id` extends
         *     this same call (ADR-0025 §5).
         *
         *     Always idempotent and always returns `200`: a session id with no
         *     prior data returns `deleted: 0`. The endpoint never reveals whether
         *     a session had data, so a client probing other sessions cannot use
         *     it as an oracle.
         *
         *     Matomo audience-measurement visits are NOT erased through this
         *     call — the daily-rotated salted hash (ADR-0025 §3) makes prior-day
         *     visits already non-attributable, and a fresh local sessionId after
         *     the call breaks linkage going forward. The privacy notice
         *     (`/confidentialite`, `/privacy`) discloses this trade-off.
         */
        delete: operations["deleteSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Format: uuid
         * @description UUID v7 string. Per ADR-0003 §6, ids are never integers.
         * @example 0190e3a4-7a2c-7c9e-8f1a-9b2d3e4f5a6b
         */
        PuzzleId: string;
        /** @description A complete mots-fléchés puzzle ready to render and play. */
        Puzzle: {
            id: components["schemas"]["PuzzleId"];
            /**
             * @description Human-facing puzzle title.
             * @example Petite grille du mardi
             */
            title: string;
            /**
             * @description BCP-47 tag (e.g. `fr`, `fr-CA`). Drives clue language and casing
             *     rules. v1 targets French mots-fléchés; the wire shape is
             *     language-neutral.
             * @example fr
             */
            language: string;
            /**
             * @description Puzzle difficulty level. Lowercase French enum values match the
             *     user-facing content language. Omitted when not yet assigned;
             *     clients must treat absence as "no difficulty set".
             * @example facile
             * @enum {string|null}
             */
            difficulty?: "facile" | "moyen" | "difficile" | null;
            /**
             * @description Sequential daily-puzzle number (e.g. 142 for the 142nd daily
             *     grid). Omitted when not yet assigned; clients must treat
             *     absence as "no number assigned".
             * @example 142
             */
            gridNumber?: number | null;
            /**
             * @description Number of columns.
             * @example 5
             */
            width: number;
            /**
             * @description Number of rows.
             * @example 5
             */
            height: number;
            /**
             * @description Cells in row-major order. Length is **at least** `width * height`;
             *     may exceed it when a cell position holds two stacked
             *     `DefinitionCell` entries (an across clue and a down clue at the
             *     same position). Clients should look up a cell by `position.row` /
             *     `position.column`, NOT by flat index `row * width + column` —
             *     that index is correct only when there are no stacked clue cells.
             */
            cells: components["schemas"]["Cell"][];
            /**
             * @description All clues, listed once. Mots-fléchés renders clue text inside a
             *     `definition` cell, but `Clue` stays separate so consumers can
             *     build a side panel, search, or tally completion without walking
             *     the cell array.
             */
            clues: components["schemas"]["Clue"][];
            /**
             * @description Hint budget for this puzzle. The client may call
             *     `POST /v1/puzzles/{puzzleId}/hints` up to this many times before
             *     the server returns 429. The budget scope (per puzzle, per player)
             *     is server-defined; the wire contract only carries the cap.
             * @example 3
             */
            hintsAllowed: number;
            /**
             * @description Hints still available for this puzzle for the current user;
             *     equals `hintsAllowed` for anonymous callers (no
             *     `__Secure-ws_session` cookie). When a cookie is presented and
             *     verified, this is `hintsAllowed - hintsUsed` for the resolved
             *     `userId`.
             * @example 2
             */
            hintsRemaining: number;
            /**
             * Format: date-time
             * @description ISO-8601 instant with timezone offset.
             * @example 2026-04-24T15:30:00Z
             */
            createdAt: string;
        };
        /**
         * @description Envelope returned by `listDailyPuzzles`. The `items` array is
         *     capped at 100 entries; clients paginate by issuing successive
         *     requests with narrower `from`/`to` ranges.
         */
        ListDailyPuzzlesResponse: {
            items: components["schemas"]["PuzzleSummary"][];
            /**
             * @description `true` when the requested range contained more than 100 items
             *     and results were truncated to the newest 100. Clients may
             *     re-query with `to` set to one day before the oldest returned
             *     `date` to page further back.
             */
            hasMore: boolean;
        };
        /**
         * @description Thin daily-puzzle summary returned by `listDailyPuzzles`. Carries
         *     only the fields the archive UI needs to render a row; the full
         *     `Puzzle` document is fetched lazily via `getDailyPuzzle` when the
         *     player opens a past grid. `id` is the deterministic UUID v7
         *     derived from `date`, matching what `getDailyPuzzle?date=` returns.
         */
        PuzzleSummary: {
            id: components["schemas"]["PuzzleId"];
            /**
             * Format: date
             * @example 2026-05-05
             */
            date: string;
            /**
             * @description Sequence number from the launch anchor (day 1 = 2026-01-01
             *     UTC). Always present on daily summaries; see
             *     `Puzzle.gridNumber` for the optional/nullable shape on the
             *     full puzzle document.
             * @example 125
             */
            gridNumber: number;
            /**
             * @description Difficulty tier for the daily. Mirrors `Puzzle.difficulty`
             *     for the same date; `null` means no tier was assigned (clients
             *     should render no badge).
             * @example facile
             * @enum {string|null}
             */
            difficulty?: "facile" | "moyen" | "difficile" | null;
            /**
             * @description Count of letter cells in the puzzle (denominator for client-side progress bars).
             * @example 28
             */
            totalLetterCells: number;
        };
        /**
         * @description Grid cell variant. `kind` discriminates: `letter` (answer cell,
         *     optionally pre-filled), `definition` (clue cell with arrow direction),
         *     `block` (unfillable decorative cell).
         */
        Cell: {
            kind: components["schemas"]["CellKind"];
            position: components["schemas"]["Position"];
        } & (components["schemas"]["LetterCell"] | components["schemas"]["DefinitionCell"] | components["schemas"]["BlockCell"]);
        /**
         * @description Discriminator for the `Cell` variants.
         * @enum {string}
         */
        CellKind: "letter" | "definition" | "block";
        /**
         * @description Player-fillable answer cell. Geometry only — the canonical solution
         *     is server-private and never appears on the wire. Distinguished from
         *     `BlockCell` by `kind`. Clients submit filled cells to
         *     `POST /v1/puzzles/{puzzleId}/validate` for verification.
         */
        LetterCell: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "letter";
            position: components["schemas"]["Position"];
        };
        /**
         * @description Mots-fléchés definition cell. Holds the clue text and an arrow
         *     showing where the answer flows.
         */
        DefinitionCell: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "definition";
            position: components["schemas"]["Position"];
            clueId: components["schemas"]["ClueId"];
            /**
             * @description Clue text rendered inside the cell.
             * @example Capitale de la France
             */
            text: string;
            arrow: components["schemas"]["Arrow"];
        };
        /** @description Unfillable decorative cell. */
        BlockCell: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "block";
            position: components["schemas"]["Position"];
        };
        /**
         * @description Arrow direction on a definition cell. `right` and `down` are the
         *     standard mots-fléchés conventions. `down-right` (first-column clue,
         *     word starts below going right) and `right-down` (first-row clue,
         *     word starts right going down) enable edge-cell interlocking.
         * @enum {string}
         */
        Arrow: "right" | "down" | "down-right" | "right-down";
        /**
         * @description Direction a clue's answer is written.
         * @enum {string}
         */
        Direction: "across" | "down";
        /** @description Zero-indexed grid coordinate. */
        Position: {
            /** @description Zero-indexed row, top to bottom. */
            row: number;
            /** @description Zero-indexed column, left to right. */
            column: number;
        };
        /**
         * Format: uuid
         * @description UUID v7 identifier of a clue.
         * @example 0190e3a4-7a2c-7c9e-8f1a-9b2d3e4f5a6c
         */
        ClueId: string;
        /**
         * @description A single clue. Mots-fléchés shows the text inside a `DefinitionCell`,
         *     but the wire keeps `Clue` separate so consumers can list, search,
         *     and tally without walking the cell array.
         */
        Clue: {
            id: components["schemas"]["ClueId"];
            direction: components["schemas"]["Direction"];
            /**
             * @description First answer cell (not the definition cell). The definition cell
             *     sits adjacent to `start` opposite `direction`.
             */
            start: components["schemas"]["Position"];
            /** @description Number of letter cells in the answer. */
            length: number;
            /**
             * @description Clue text. Duplicated from `DefinitionCell.text` on purpose —
             *     cheap on a 225-cell grid and spares clients a join.
             */
            text: string;
        };
        /**
         * @description Request body for `POST /v1/puzzles/{puzzleId}/hints`. Identifies
         *     the cell whose canonical letter the caller wants to reveal.
         *     `(row, column)` MUST point at a `letter`-kind cell within the
         *     puzzle bounds; pointing at a definition or block cell, or out of
         *     bounds, is a 400 `invalid-coord` and does NOT decrement the
         *     budget.
         */
        RevealCellHintRequest: {
            /**
             * @description Zero-indexed row of the cell to reveal.
             * @example 3
             */
            row: number;
            /**
             * @description Zero-indexed column of the cell to reveal.
             * @example 5
             */
            column: number;
        };
        /**
         * @description Response body for `DELETE /v1/sessions/{sessionId}` on a 200.
         *     Reports the number of rows the server actually deleted across all
         *     tables that reference the session. `0` is a valid success — the
         *     session had no server-side data (no hints used, no cooldown rows written).
         */
        DeleteSessionResponse: {
            /**
             * @description Total rows deleted (across all tables).
             * @example 3
             */
            deleted: number;
        };
        /**
         * @description Response body for `POST /v1/puzzles/{puzzleId}/hints` on a 200.
         *     Echoes the requested coordinate alongside the canonical letter so
         *     the client can correlate the response with the cell to update
         *     even if multiple reveals are in flight.
         */
        RevealCellHintResult: {
            /**
             * @description Echo of the request's `row`.
             * @example 3
             */
            row: number;
            /**
             * @description Echo of the request's `column`.
             * @example 5
             */
            column: number;
            /**
             * @description Canonical solution letter at `(row, column)`, single uppercase
             *     A-Z code point. Diacritics are normalized server-side.
             * @example P
             */
            letter: string;
            /**
             * @description Hints left after this call. `0` means the next call will return
             *     a 429 with `type` `https://bliss.example/errors/hint-budget-exhausted`.
             * @example 2
             */
            hintsRemaining: number;
        };
        /**
         * @description Request body for `POST /v1/puzzles/{puzzleId}/validate`. Carries the
         *     cells the client wants to verify. Cleared / unfilled letter cells are
         *     absent — do NOT send `letter: null`. Order is irrelevant; the server
         *     keys by `(row, column)`. Duplicate `(row, column)` entries are a 400.
         * @example {
         *       "filledCells": [
         *         {
         *           "row": 0,
         *           "column": 1,
         *           "letter": "P"
         *         },
         *         {
         *           "row": 0,
         *           "column": 3,
         *           "letter": "G"
         *         },
         *         {
         *           "row": 0,
         *           "column": 5,
         *           "letter": "S"
         *         }
         *       ]
         *     }
         */
        ValidatePuzzleRequest: {
            /**
             * @description Submitted letters. `maxItems` matches the protocol-level upper
             *     bound on letter cells in a `Puzzle` (`width × height` with
             *     `width`, `height` ≤ 50).
             */
            filledCells: components["schemas"]["FilledCell"][];
        };
        /**
         * @description A single client-submitted letter for a letter cell. `(row, column)`
         *     must point at a `letter`-kind cell in the puzzle; pointing at a
         *     definition or block cell is a 400.
         */
        FilledCell: {
            /** @example 0 */
            row: number;
            /** @example 1 */
            column: number;
            /**
             * @description Single uppercase A-Z code point. Diacritics are normalized
             *     client-side before submission.
             * @example P
             */
            letter: string;
        };
        /**
         * @description Validation outcome. The server intentionally returns positions only,
         *     never the canonical letter, so the response cannot be used to
         *     reconstruct the solution in a single call.
         */
        ValidatePuzzleResult: {
            /**
             * @description True iff every letter cell is filled and matches the canonical
             *     solution.
             * @example false
             */
            solved: boolean;
            /**
             * @description Positions where the submitted letter is wrong OR the letter cell
             *     was not filled by the client. Empty iff `solved` is true.
             * @example [
             *       {
             *         "row": 4,
             *         "column": 1
             *       },
             *       {
             *         "row": 6,
             *         "column": 9
             *       }
             *     ]
             */
            incorrectCells: components["schemas"]["Position"][];
        };
        /**
         * @description RFC 7807 error envelope (ADR-0003 §6). Additional members per
         *     RFC 7807 §3.2 may appear; clients tolerate them.
         */
        Problem: {
            /**
             * Format: uri
             * @description Stable URI for the error class. Clients route on `type`, never on
             *     `title` or `detail`.
             * @example https://bliss.example/errors/puzzle-not-found
             */
            type: string;
            /**
             * @description Short, human-readable summary of the error class.
             * @example Puzzle not found
             */
            title: string;
            /**
             * @description HTTP status code, repeated for clients that lose it.
             * @example 404
             */
            status: number;
            /** @description Human-readable explanation specific to this occurrence. */
            detail?: string;
            /**
             * Format: uri-reference
             * @description URI reference identifying the specific occurrence.
             */
            instance?: string;
        };
        /**
         * @description A single clue→answer pair for the home teaser (ADR-0073). Both
         *     fields are always present; the `answer` ships in plaintext because
         *     the teaser validates client-side (see `sampleWords`).
         */
        SampleWord: {
            /**
             * @description One clue text for the sampled word.
             * @example Capitale de la France
             */
            clue: string;
            /**
             * @description The corpus word's folded surface form — uppercase ASCII A–Z, per
             *     the `Word.text` invariant (ADR-0073 §1).
             * @example PARIS
             */
            answer: string;
        };
    };
    responses: never;
    parameters: {
        /** @description UUID v7 identifier of the puzzle. */
        PuzzleId: components["schemas"]["PuzzleId"];
        /**
         * @description UUID v7 identifying the calling player's session. When present,
         *     the server biases clue selection on cache miss away from clues
         *     recently used by the same session (per ADR-0031 "per-session clue
         *     cooldown"). When absent, no cooldown is applied and clue
         *     selection is unaffected. Cache hits are unchanged regardless.
         *
         *     Non-UUID values, or a UUID equal to the reserved daily-bucket
         *     sentinel `00000000-0000-7000-8000-000000000000`, produce a 400
         *     `invalid-session-id` response (poisoning guard per ADR-0031
         *     Threat model § Tampering).
         */
        OptionalSessionId: string;
        /**
         * @description Number of columns to generate. Defaults to 15 when omitted, matching
         *     the daily landscape grid. Valid range is 5..15 inclusive; values
         *     outside that range — or non-integers — produce a 400 with problem
         *     type `https://bliss.example/errors/invalid-puzzle-dimensions`. The
         *     bounds keep the CSP solver's vocabulary needs and per-request time
         *     budget reasonable.
         */
        PuzzleWidth: number;
        /**
         * @description Number of rows to generate. Defaults to 12 when omitted, matching
         *     the daily landscape grid. Valid range is 5..15 inclusive; values
         *     outside that range — or non-integers — produce a 400 with problem
         *     type `https://bliss.example/errors/invalid-puzzle-dimensions`.
         */
        PuzzleHeight: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getPuzzle: {
        parameters: {
            query?: {
                /**
                 * @description Number of columns to generate. Defaults to 15 when omitted, matching
                 *     the daily landscape grid. Valid range is 5..15 inclusive; values
                 *     outside that range — or non-integers — produce a 400 with problem
                 *     type `https://bliss.example/errors/invalid-puzzle-dimensions`. The
                 *     bounds keep the CSP solver's vocabulary needs and per-request time
                 *     budget reasonable.
                 */
                width?: components["parameters"]["PuzzleWidth"];
                /**
                 * @description Number of rows to generate. Defaults to 12 when omitted, matching
                 *     the daily landscape grid. Valid range is 5..15 inclusive; values
                 *     outside that range — or non-integers — produce a 400 with problem
                 *     type `https://bliss.example/errors/invalid-puzzle-dimensions`.
                 */
                height?: components["parameters"]["PuzzleHeight"];
            };
            header?: {
                /**
                 * @description UUID v7 identifying the calling player's session. When present,
                 *     the server biases clue selection on cache miss away from clues
                 *     recently used by the same session (per ADR-0031 "per-session clue
                 *     cooldown"). When absent, no cooldown is applied and clue
                 *     selection is unaffected. Cache hits are unchanged regardless.
                 *
                 *     Non-UUID values, or a UUID equal to the reserved daily-bucket
                 *     sentinel `00000000-0000-7000-8000-000000000000`, produce a 400
                 *     `invalid-session-id` response (poisoning guard per ADR-0031
                 *     Threat model § Tampering).
                 */
                "X-Session-Id"?: components["parameters"]["OptionalSessionId"];
            };
            path: {
                /** @description UUID v7 identifier of the puzzle. */
                puzzleId: components["parameters"]["PuzzleId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description Puzzle found. Canonical sample at
             *     `grid/api/examples/get-puzzle-200.json` is the contract-test
             *     fixture for both sides of the wire. The example is a 10×10
             *     grid (smaller than the daily default of 15×12) chosen to keep
             *     the file readable; the wire shape is identical at any size,
             *     and requesting `?width=7&height=7` produces an analogous 7×7
             *     document with the same fields.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Puzzle"];
                };
            };
            /**
             * @description Request is malformed. RFC 7807 body. Variants:
             *     - Path parameter `puzzleId` is not a valid UUID
             *       (`type` = `https://bliss.example/errors/invalid-puzzle-id`).
             *     - Query parameter `width` or `height` is not an integer or is
             *       outside the supported 5..15 range
             *       (`type` = `https://bliss.example/errors/invalid-puzzle-dimensions`).
             *     - Header `X-Session-Id` is present but not a valid UUID, or
             *       equals the reserved daily-bucket sentinel
             *       `00000000-0000-7000-8000-000000000000` (poisoning guard per
             *       ADR-0031)
             *       (`type` = `https://bliss.example/errors/invalid-session-id`).
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /**
             * @description Puzzle generation failed. The requested constraints (grid size,
             *     word list, interlocking rules) are unsatisfiable within the
             *     attempt budget. RFC 7807 body;
             *     `type` is `https://bliss.example/errors/puzzle-generation-failed`.
             */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getDailyPuzzle: {
        parameters: {
            query?: {
                /**
                 * @description ISO-8601 calendar date (`YYYY-MM-DD`) in UTC. When omitted the
                 *     server uses today's UTC date. Future dates are accepted; the
                 *     endpoint returns 404 if the daily worker has not yet produced a
                 *     row for that date (see endpoint description).
                 */
                date?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daily puzzle resolved for the requested date. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Puzzle"];
                };
            };
            /**
             * @description The `date` query parameter is not a valid ISO-8601 calendar
             *     date. RFC 7807 body;
             *     `type` is `https://bliss.example/errors/invalid-puzzle-date`.
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /**
             * @description No daily puzzle exists for the requested date. The worker job that
             *     pre-generates daily grids has not yet produced (or failed to produce)
             *     a puzzle for this date. Clients should retry shortly or surface a
             *     user-facing "daily not yet available" message.
             */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "https://bliss.example/errors/no-daily-puzzle",
                     *       "title": "Aucune grille du jour disponible",
                     *       "status": 404,
                     *       "detail": "La grille du jour n'a pas encore été générée pour cette date."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listDailyPuzzles: {
        parameters: {
            query?: {
                /**
                 * @description ISO-8601 calendar date inclusive. Defaults to 31 days before
                 *     `to` when omitted. Values earlier than the launch anchor are
                 *     clamped to the anchor.
                 */
                from?: string;
                /**
                 * @description ISO-8601 calendar date inclusive. Defaults to today UTC.
                 *     Future values are clamped to today.
                 */
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description List resolved. `items` is sorted DESC by `date`. May be empty
             *     (e.g. range entirely before launch anchor, or no row exists
             *     for any date in the range because the worker hasn't filled it
             *     yet).
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListDailyPuzzlesResponse"];
                };
            };
            /**
             * @description `from` or `to` is not a valid ISO-8601 date. RFC 7807;
             *     `type` is `https://bliss.example/errors/invalid-puzzle-date`.
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    sampleWords: {
        parameters: {
            query?: {
                /**
                 * @description Minimum answer length (inclusive), in letters. Defaults to 3.
                 *     Valid range is 3..6 inclusive; values outside that range, a
                 *     non-integer, or a `minLen` greater than `maxLen` produce a 400
                 *     with problem type
                 *     `https://bliss.example/errors/invalid-sample-bounds`.
                 */
                minLen?: number;
                /**
                 * @description Maximum answer length (inclusive), in letters. Defaults to 6.
                 *     Valid range is 3..6 inclusive; values outside that range, a
                 *     non-integer, or a `maxLen` smaller than `minLen` produce a 400
                 *     with problem type
                 *     `https://bliss.example/errors/invalid-sample-bounds`.
                 */
                maxLen?: number;
                /**
                 * @description Number of clue→answer pairs to return. Defaults to 8. Bounded
                 *     server-side to a maximum of 50; requests above the ceiling are
                 *     clamped to 50 (an unbounded `count` would let a caller drain the
                 *     corpus answer-by-answer, ADR-0073 §4). Non-positive or
                 *     non-integer values produce a 400 with problem type
                 *     `https://bliss.example/errors/invalid-sample-bounds`. Fewer than
                 *     `count` pairs may be returned when the corpus holds fewer
                 *     distinct headwords in the requested length range.
                 */
                count?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description Sample resolved. A bare array of `SampleWord` pairs, deduped by
             *     headword and randomly drawn from the requested length range. May
             *     hold fewer than `count` entries when the corpus is thin for the
             *     range.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SampleWord"][];
                };
            };
            /**
             * @description Request bounds are malformed. RFC 7807 body;
             *     `type` is `https://bliss.example/errors/invalid-sample-bounds`.
             *     Variants: `minLen`/`maxLen`/`count` is non-integer or
             *     out-of-range, or `minLen` exceeds `maxLen`.
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    revealCellHint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID v7 identifier of the puzzle. */
                puzzleId: components["parameters"]["PuzzleId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevealCellHintRequest"];
            };
        };
        responses: {
            /**
             * @description Hint consumed. Body reports the canonical letter at the
             *     requested cell and the remaining budget for this
             *     `(puzzle, player)`.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevealCellHintResult"];
                };
            };
            /**
             * @description Request is malformed. RFC 7807. Variants:
             *     - Path parameter `puzzleId` is not a valid UUID
             *       (`type` = `https://bliss.example/errors/invalid-puzzle-id`).
             *     - Request body missing or unparseable
             *       (`type` = `https://bliss.example/errors/invalid-request-body`).
             *     - `(row, column)` is out of bounds or points at a non-letter
             *       cell (`type` = `https://bliss.example/errors/invalid-coord`).
             *       The hint budget is NOT decremented in this case.
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /**
             * @description No valid `__Secure-ws_session` cookie. The session is missing,
             *     unparseable, or has been revoked. RFC 7807;
             *     `type` is `https://bliss.example/errors/auth-required`.
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /**
             * @description No puzzle with this id. RFC 7807;
             *     `type` is `https://bliss.example/errors/puzzle-not-found`.
             */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /**
             * @description Hint budget exhausted for this `(puzzle, player)`. RFC 7807;
             *     `type` is `https://bliss.example/errors/hint-budget-exhausted`.
             *     The body's `detail` SHOULD echo `hintsRemaining: 0`.
             */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    validatePuzzle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID v7 identifier of the puzzle. */
                puzzleId: components["parameters"]["PuzzleId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidatePuzzleRequest"];
            };
        };
        responses: {
            /**
             * @description Validation completed. `incorrectCells` is empty iff `solved` is
             *     true. Cells the client did not fill appear in `incorrectCells`
             *     alongside cells whose submitted letter is wrong.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidatePuzzleResult"];
                };
            };
            /**
             * @description Request invalid: position out of range, position pointing at a
             *     non-letter cell, `letter` not a single uppercase A-Z, or
             *     duplicate `(row, column)`. RFC 7807;
             *     `type` is `https://bliss.example/errors/invalid-validate-request`.
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /**
             * @description No puzzle with this id. RFC 7807;
             *     `type` is `https://bliss.example/errors/puzzle-not-found`.
             */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    deleteSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID identifying the session to erase. */
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description Erasure completed. Body reports the number of rows deleted
             *     (across all server-side tables). A zero count is a valid
             *     success — it means the session had no server-side data
             *     (no hints used, no cooldown rows written).
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteSessionResponse"];
                };
            };
            /**
             * @description Path parameter `sessionId` is not a valid UUID. RFC 7807;
             *     `type` is `https://bliss.example/errors/invalid-session-id`.
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
