/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/lobbies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a new lobby.
         * @description Creates a new lobby in WAITING with the calling player as the sole
         *     member and owner. The client supplies `ownerSessionId` (UUID v7,
         *     generated client-side per ADR-0018 §"sessions") and `ownerPseudonym`.
         *     The server mints `lobbyId` (base58 nanoid, ADR-0020) and returns the
         *     full `Lobby` resource.
         *
         *     The 201 response includes a `Location` header pointing at the
         *     canonical read URL.
         */
        post: operations["createLobby"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/lobbies/by-code/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Resolve a lobby from its human-friendly join code.
         * @description Powers the Accueil "Rejoindre avec un code" flow. The frontend
         *     passes the typed code; on success the response carries the full
         *     `Lobby` resource and the client navigates to `/lobby/{id}` using
         *     the returned `id`. The WebSocket join still goes through the
         *     existing AsyncAPI surface keyed by `lobbyId`.
         */
        get: operations["getLobbyByCode"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/lobbies/{lobbyId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read current lobby state.
         * @description Returns the full `Lobby` snapshot. Used by the frontend route loader
         *     to bootstrap the WebSocket connection: the WS opens AFTER the loader
         *     confirms the lobby exists and learns the current lifecycle state.
         */
        get: operations["getLobby"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{sessionId}/lobbies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List lobbies the caller's session is a member of.
         * @description Powers the Accueil "Mes parties" card so a returning player can pick
         *     up yesterday's lobby without bookmarking the URL. Returns lobbies
         *     that have entered play — `IN_PROGRESS` or `COMPLETED` — ordered by
         *     `lastActivityAt` descending so the most recently touched lobby is
         *     first. `WAITING` (un-started) lobbies are excluded because they are
         *     "salons d'attente", not "parties"; surfacing them produced confusing
         *     404 toasts when the WAITING TTL evicted them between fetch and click
         *     (ADR-0039 amendment 2026-05-12). WAITING lobbies remain reachable
         *     via the direct lobby URL or the invite code.
         *
         *     Empty array is the "no lobbies" answer — there is no 404 here,
         *     which would leak whether the session has ever played.
         *
         *     Not paginated: a single anonymous session is naturally capped at a
         *     handful of lobbies and pagination would be premature complexity.
         */
        get: operations["listLobbiesForSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Erase server-side lobby data for a session (RGPD Article 17).
         * @description Cascades the three-rule erasure documented in ADR-0039 across every
         *     lobby the session is a member of:
         *
         *     1. Erased user owns the lobby and is the sole player → the lobby is
         *        deleted outright.
         *     2. Erased user owns the lobby with at least one remaining player →
         *        ownership transfers to the earliest-joined remaining player, the
         *        erased user is removed, and their cell entries are anonymised
         *        (attribution dropped; letters retained so the puzzle stays
         *        coherent for the others).
         *     3. Erased user is a non-owner player → they are removed and their
         *        entries are anonymised; the lobby and its owner are unchanged.
         *
         *     Always idempotent and always returns `200`. A session id with no
         *     prior data returns all-zero counts. Like the grid-api sibling
         *     (`SessionRoute.kt`), the endpoint never reveals whether a session
         *     had data — disclosing presence would itself be a leak.
         *
         *     The frontend's "Effacer mes données" button fans this call out
         *     together with grid-api's `DELETE /v1/sessions/{sessionId}`; both
         *     must succeed for the UI to claim data was erased.
         */
        delete: operations["deleteSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/lobbies/players/rebind": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rebind anon lobby seats to the authenticated user.
         * @description Cookie-authed. Updates every lobby seat where `sessionId == anonSessionId`
         *     AND `userId` is null: sets `userId` to the authenticated user and
         *     refreshes the seat pseudonym from the user's current displayName.
         *     Idempotent — re-running with the same body is a no-op.
         */
        post: operations["rebindLobbySessions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/lobbies/players/unbind": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Unbind authenticated lobby seats before sign-out.
         * @description Cookie-authed. Updates every lobby seat where `userId == cookie.userId`:
         *     clears `userId` and sets the seat pseudonym to the supplied
         *     `anonPseudonym`. Called by the frontend before invoking
         *     `POST /v1/auth/logout`. Idempotent.
         */
        post: operations["unbindLobbySessions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description 8-char base58 nanoid (URL-safe; no `0`, `O`, `I`, `l`). Documented
         *     exception to ADR-0003 §6's UUID v7 default per ADR-0020 — lobbies
         *     embed their id in human-shareable URLs, where 36-char UUIDs are
         *     unwieldy. Mirrors `LobbyId` in `game/api/asyncapi.yaml`; keep in sync.
         * @example 7gQ2xK9p
         */
        LobbyId: string;
        /**
         * Format: uuid
         * @description UUID v7 string per ADR-0003 §6. Generated client-side on first visit
         *     and persisted in `localStorage`. Mirrors `SessionId` in
         *     `game/api/asyncapi.yaml`; keep in sync.
         * @example 0190e3a4-7a2c-7c9e-8f1a-9b2d3e4f5a6b
         */
        SessionId: string;
        /**
         * @description Player display name. Not unique within a lobby. Leading / trailing
         *     whitespace is rejected. Mirrors `Pseudonym` in
         *     `game/api/asyncapi.yaml`; keep in sync.
         * @example Joueur 1234
         */
        Pseudonym: string;
        /**
         * Format: date-time
         * @description ISO-8601 instant with timezone offset (ADR-0003 §6).
         * @example 2026-05-02T15:30:00Z
         */
        Instant: string;
        /**
         * @description Lobby lifecycle (ADR-0018). Mirrors `LobbyLifecycleState` in `game/api/asyncapi.yaml`.
         * @enum {string}
         */
        LobbyLifecycleState: "WAITING" | "IN_PROGRESS" | "COMPLETED";
        /**
         * @description Dimensions chosen by the lobby owner before start. Mirrors `GridConfig`
         *     in `game/api/asyncapi.yaml`; keep in sync.
         */
        GridConfig: {
            /**
             * @description Number of columns.
             * @example 7
             */
            width: number;
            /**
             * @description Number of rows.
             * @example 7
             */
            height: number;
        };
        /**
         * @description A player currently holding a slot in the lobby. Mirrors `Player` in
         *     `game/api/asyncapi.yaml`; keep in sync.
         */
        Player: {
            sessionId: components["schemas"]["SessionId"];
            pseudonym: components["schemas"]["Pseudonym"];
            joinedAt: components["schemas"]["Instant"];
        };
        /**
         * @description Game-context projection of a puzzle. Carries every field a client
         *     needs to render and play. Owned by game/ — not a $ref into grid/
         *     (ADR-0001 §1 forbids cross-context file dependencies). The server
         *     fetches from grid/ on startGame and forwards the document verbatim.
         *     Mirrors `GamePuzzle` in `game/api/asyncapi.yaml`; keep in sync.
         */
        GamePuzzle: {
            /**
             * Format: uuid
             * @description UUID v7 puzzle identifier.
             * @example 0190e3a4-7a2c-7c9e-8f1a-9b2d3e4f5a6c
             */
            id: string;
            /** @example Petite grille du mardi */
            title: string;
            /**
             * @description BCP-47 tag.
             * @example fr
             */
            language: string;
            /**
             * @description Number of columns.
             * @example 5
             */
            width: number;
            /**
             * @description Number of rows.
             * @example 5
             */
            height: number;
            /** @description Cells in row-major order; look up by position.row/position.column. */
            cells: components["schemas"]["GameCell"][];
            clues: components["schemas"]["GameClue"][];
            /**
             * @description Hint budget for this puzzle. Mirrors `Puzzle.hintsAllowed` in
             *     `grid/api/openapi.yaml`; forwarded verbatim from grid/ on startGame.
             * @example 3
             */
            hintsAllowed: number;
            createdAt: components["schemas"]["Instant"];
        };
        /**
         * @description Grid cell. `kind` discriminates letter / definition / block. Mirrors
         *     `GameCell` in `game/api/asyncapi.yaml`; keep in sync.
         */
        GameCell: {
            kind: components["schemas"]["GameCellKind"];
            position: components["schemas"]["GamePosition"];
        } & (components["schemas"]["GameLetterCell"] | components["schemas"]["GameDefinitionCell"] | components["schemas"]["GameBlockCell"]);
        /**
         * @description Discriminator for `GameCell` variants.
         * @enum {string}
         */
        GameCellKind: "letter" | "definition" | "block";
        /**
         * @description Player-fillable answer cell. The canonical solution is server-private
         *     and never carried on the wire. Player input flows in via the
         *     `cellUpdate` WebSocket frame and is rebroadcast as `cellUpdated`. On
         *     solve, `gameSolved.finalEntries` carries the full solved grid — the
         *     only post-completion broadcast of canonical letters. Mirrors
         *     `GameLetterCell` in `game/api/asyncapi.yaml`; keep in sync per
         *     ADR-0001 §1 (no cross-context $ref).
         */
        GameLetterCell: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "letter";
            position: components["schemas"]["GamePosition"];
        };
        /**
         * @description Mots-fleches definition cell. Carries 1 clue (the common case) or 2
         *     clues (the corner-cell idiom — an across clue and a down clue stacked
         *     at one position). Mirrors `GameDefinitionCell` in
         *     `game/api/asyncapi.yaml`; keep in sync.
         */
        GameDefinitionCell: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "definition";
            position: components["schemas"]["GamePosition"];
            clues: components["schemas"]["GameDefinitionClue"][];
        };
        /** @description A single clue carried by a `GameDefinitionCell`. */
        GameDefinitionClue: {
            /**
             * Format: uuid
             * @description UUID v7 clue identifier.
             * @example 0190e3a4-7a2c-7c9e-8f1a-9b2d3e4f5a6d
             */
            id: string;
            /** @example Capitale de la France */
            text: string;
            arrow: components["schemas"]["GameArrow"];
        };
        /** @description Unfillable decorative cell. */
        GameBlockCell: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "block";
            position: components["schemas"]["GamePosition"];
        };
        /**
         * @description Arrow direction on a mots-fleches definition cell.
         * @enum {string}
         */
        GameArrow: "right" | "down" | "down-right" | "right-down";
        /** @description Zero-indexed grid coordinate. */
        GamePosition: {
            /** @description Zero-indexed row, top to bottom. */
            row: number;
            /** @description Zero-indexed column, left to right. */
            column: number;
        };
        /** @description A locked cell plus the session that first locked it (first-writer-wins on crossings). */
        LockedCell: {
            /** @description Zero-indexed row, top to bottom. */
            row: number;
            /** @description Zero-indexed column, left to right. */
            column: number;
            lockedBy: components["schemas"]["SessionId"];
        };
        /** @description A single clue listed in `GamePuzzle.clues`. */
        GameClue: {
            /**
             * Format: uuid
             * @description UUID v7 clue identifier.
             * @example 0190e3a4-7a2c-7c9e-8f1a-9b2d3e4f5a6e
             */
            id: string;
            direction: components["schemas"]["GameClueDirection"];
            start: components["schemas"]["GamePosition"];
            /** @description Number of letter cells in the answer. */
            length: number;
            text: string;
        };
        /**
         * @description Direction a clue's answer is written.
         * @enum {string}
         */
        GameClueDirection: "across" | "down";
        /**
         * @description Active game embedded in `Lobby.game` while IN_PROGRESS or COMPLETED.
         *     `completedAt` is in `required` because the field is always present on
         *     the wire — `null` (still in progress) and a timestamp (solved) are
         *     both meaningful values. `entries` carries every letter typed so far
         *     (server-authoritative) so a client refreshing the page in mid-game
         *     rehydrates the grid from the REST snapshot before the WebSocket
         *     opens. Cleared cells are absent from the list; entries are sorted
         *     by row then column for stable rendering. `lockedPositions` mirrors
         *     the cumulative server-locked cells (every word validated correct
         *     so far) so the same refresh path renders read-only cells without
         *     waiting for a WebSocket replay; always emitted (empty list when
         *     no word has been locked). `presence` is the ephemeral cursor map
         *     for currently-connected players; optional and absent or empty
         *     when state is WAITING/COMPLETED. Mirrors `GameSession` in
         *     `game/api/asyncapi.yaml`; keep in sync.
         */
        GameSession: {
            puzzle: components["schemas"]["GamePuzzle"];
            /** @description Every cell typed so far. Empty list when no player has typed yet. */
            entries: components["schemas"]["CellEntry"][];
            /**
             * @description Cumulative cells locked by server-side word validation, each with
             *     the per-cell `lockedBy` session that first locked it (first-writer-
             *     wins on crossings, per ADR-0086). Order is row then column for
             *     diff-friendly snapshots. Empty list when no word has been locked.
             */
            lockedPositions: components["schemas"]["LockedCell"][];
            startedAt: components["schemas"]["Instant"];
            /** @description Set once the lobby reaches COMPLETED; `null` while IN_PROGRESS. */
            completedAt: components["schemas"]["Instant"] | null;
            /**
             * @description Ephemeral cursor positions of currently-connected players.
             *     Empty or absent when state is WAITING/COMPLETED. Not persisted
             *     (lives in `SessionManager`'s in-memory map per ADR-0018 §3).
             *     Mirrors `lobbyState.game.presence` on the WebSocket snapshot.
             */
            presence?: components["schemas"]["PresenceEntry"][];
        };
        /**
         * @description A single placed letter in the canonical entries list. Used by
         *     `GameSession.entries` to rehydrate a refreshing client's grid.
         *     `letter` is always non-null — cleared cells are absent from the
         *     list. `sessionId` and `writtenAt` mirror the per-cell `cellUpdated`
         *     WebSocket event so a future per-author UI tint can colour each
         *     entry. Mirrors `CellEntry` in `game/api/asyncapi.yaml`; keep in sync.
         */
        CellEntry: {
            sessionId: components["schemas"]["SessionId"];
            /** @example 0 */
            row: number;
            /** @example 3 */
            column: number;
            /**
             * @description Always non-null. Cleared cells are absent from the list.
             * @example P
             */
            letter: string;
            writtenAt: components["schemas"]["Instant"];
        };
        /**
         * @description Ephemeral cursor position of one currently-connected player. Carried
         *     by `GameSession.presence` so a client bootstrapping via REST sees
         *     peer cursors immediately, before opening the WebSocket. `row`,
         *     `column`, `direction` are all nullable — `null` means the player
         *     has no cell focused. Absence from the list means the player is not
         *     connected; per ADR-0003 §6, absence and `null` are distinct.
         *     Carries no domain meaning; not persisted. Mirrors `PresenceEntry`
         *     in `game/api/asyncapi.yaml`; keep in sync.
         */
        PresenceEntry: {
            sessionId: components["schemas"]["SessionId"];
            /**
             * @description Zero-indexed row of the focused cell; `null` when no cell is focused.
             * @example 0
             */
            row: number | null;
            /**
             * @description Zero-indexed column of the focused cell; `null` when no cell is focused.
             * @example 3
             */
            column: number | null;
            /** @description Direction the player is currently solving; `null` when no cell is focused. Lets peers tint the whole word. */
            direction: components["schemas"]["GameClueDirection"] | null;
        };
        /**
         * @description Full lobby snapshot. `game` is in `required` because the field is
         *     always present on the wire — `null` (state == WAITING) and a populated
         *     `GameSession` (state in {IN_PROGRESS, COMPLETED}) are both meaningful.
         *     ADR-0003 §6: absence and `null` are distinct.
         */
        Lobby: {
            id: components["schemas"]["LobbyId"];
            ownerSessionId: components["schemas"]["SessionId"];
            /**
             * @description Up to 8 players (ADR-0018). Wire shape is an array, NOT a
             *     map-keyed-by-sessionId — JSON object keys are unordered, an array
             *     preserves join order for stable rendering.
             */
            players: components["schemas"]["Player"][];
            state: components["schemas"]["LobbyLifecycleState"];
            gridConfig: components["schemas"]["GridConfig"];
            /** @description Null while WAITING; populated while IN_PROGRESS or COMPLETED. */
            game: components["schemas"]["GameSession"] | null;
            /**
             * @description Human-friendly join code surfaced to non-owner players (the
             *     Accueil "Rejoindre avec un code" flow renders this in the
             *     input). Six uppercase alphanumeric characters, drawn from the
             *     unambiguous Crockford-style alphabet (no `0`/`O`, `1`/`I`,
             *     `L`) so a player reading the code aloud cannot land on a
             *     different lobby. Always present for lobbies created after the
             *     join-by-code wave (PR #262). Will be promoted to `required`
             *     in phase 3 once all clients expect the field.
             * @example A2B3C4
             */
            code?: string;
            /**
             * @description Optional human-friendly label set by the lobby owner at
             *     creation (e.g. "Game A", "Mardi soir"). Powers the Accueil
             *     "Mes parties" card so a returning player recognises yesterday's
             *     lobby at a glance; when absent the UI falls back to a
             *     date-derived label. Per ADR-0003 §6, optional means absent OR
             *     present — never `null` on the wire.
             * @example Mardi soir
             */
            title?: string;
        };
        /**
         * @description Compact view of a lobby for the "Mes parties" listing. Carries just
         *     enough to render a row in the Accueil card (label, code, grid size,
         *     recency, puzzle progress) without paying the cost of the full
         *     `Lobby` snapshot — the `game` payload is intentionally omitted. The
         *     frontend hydrates the full lobby through `GET /v1/lobbies/{lobbyId}`
         *     when the player clicks through. `title` is optional with the same
         *     wire semantics as `Lobby.title` (absent OR present, never `null`).
         */
        LobbySummary: {
            id: components["schemas"]["LobbyId"];
            /**
             * @description Join code mirroring `Lobby.code`. Required here because every
             *     lobby surfaced by this endpoint is post-PR-#262 and always has
             *     a code; the frontend renders it next to the title in the card.
             * @example A2B3C4
             */
            code: string;
            state: components["schemas"]["LobbyLifecycleState"];
            gridConfig: components["schemas"]["GridConfig"];
            /**
             * @description Number of players currently holding a slot — the total roster
             *     size, including players who are offline right now. Computed by
             *     the adapter so the summary endpoint avoids loading the full
             *     player list. Contrast with `connectedCount`, which counts only
             *     the subset whose WebSocket session is live.
             * @example 3
             */
            playerCount: number;
            /**
             * @description Subset of `playerCount` whose WebSocket session is currently
             *     connected. Drives the `X / Y` display on the Accueil "Mes
             *     parties" surface where X = connected, Y = `playerCount` (total
             *     roster including offline). When the backend has no connection
             *     registry signal for a player, that player is treated as
             *     disconnected (conservative). Minimum 0; maximum `playerCount`
             *     (frontend may clamp defensively but server must enforce).
             * @example 2
             */
            connectedCount: number;
            lastActivityAt: components["schemas"]["Instant"];
            progress: components["schemas"]["LobbyProgress"];
            /**
             * @description Optional label mirroring `Lobby.title`. Absent when the owner
             *     did not set one at creation; never `null` on the wire.
             * @example Mardi soir
             */
            title?: string;
        };
        /**
         * @description Puzzle progress projection for a lobby's `GameSession`. `solvedCells`
         *     counts letter cells whose typed entry matches the canonical answer;
         *     `totalCells` counts answerable letter cells in the puzzle. Always
         *     present in `LobbySummary` because the endpoint only lists
         *     `IN_PROGRESS` / `COMPLETED` lobbies, both of which carry a
         *     `GameSession`. Drives the per-row progress bar on the Accueil "Mes
         *     parties" surface.
         */
        LobbyProgress: {
            /**
             * @description Letter cells whose typed entry matches the canonical answer.
             * @example 12
             */
            solvedCells: number;
            /**
             * @description Letter cells in the puzzle that have an answer to be solved.
             * @example 50
             */
            totalCells: number;
        };
        /**
         * @description Request body for `POST /v1/lobbies`.
         * @example {
         *       "ownerSessionId": "0190e3a4-7a2c-7c9e-8f1a-9b2d3e4f5a6b",
         *       "ownerPseudonym": "Joueur 1234",
         *       "title": "Mardi soir"
         *     }
         */
        CreateLobbyRequest: {
            ownerSessionId: components["schemas"]["SessionId"];
            /**
             * @description Accepted for wire-compatibility but unused server-side (ADR-0083):
             *     the authed create path derives the owner's display name from the
             *     verified session instead.
             */
            ownerPseudonym: components["schemas"]["Pseudonym"];
            /**
             * @description Optional human-friendly label for the lobby. Surfaced on the
             *     "Mes parties" card. Per ADR-0003 §6, optional means absent OR
             *     present — never `null` on the wire; omit the field entirely to
             *     create an untitled lobby.
             * @example Mardi soir
             */
            title?: string;
        };
        /**
         * @description Response body for `DELETE /v1/sessions/{sessionId}` on a 200.
         *     Reports the per-rule counts of the three-rule cascade documented
         *     in ADR-0039. All-zero is a valid success — the session had no
         *     server-side data.
         */
        DeleteSessionResponse: {
            /**
             * @description Number of lobbies deleted because the erased session was the
             *     sole owner-player (Rule 1).
             * @example 1
             */
            deletedLobbies: number;
            /**
             * @description Number of lobbies whose ownership was transferred to the
             *     earliest-joined remaining player because the erased session
             *     was the owner with at least one other player (Rule 2).
             * @example 1
             */
            transferredLobbies: number;
            /**
             * @description Number of lobby memberships removed for the erased session
             *     (sum across Rules 2 and 3 — i.e. every lobby the session was
             *     a member of and that was not deleted outright).
             * @example 2
             */
            removedPlayerships: number;
            /**
             * @description Number of `lobby_cell_entries` rows whose author attribution
             *     was dropped (letters retained, `writtenBySessionId` cleared)
             *     so surviving lobbies stay coherent for the remaining players.
             * @example 7
             */
            anonymisedEntries: number;
        };
        /**
         * @description RFC 7807 error envelope (ADR-0003 §6). Additional members per
         *     RFC 7807 §3.2 may appear; clients tolerate them.
         */
        Problem: {
            /**
             * Format: uri
             * @description Stable URI for the error class. Clients route on `type`, never on
             *     `title` or `detail`.
             * @example https://bliss.example/errors/lobby-not-found
             */
            type: string;
            /**
             * @description Short, human-readable summary of the error class.
             * @example Lobby not found
             */
            title: string;
            /**
             * @description HTTP status code, repeated for clients that lose it.
             * @example 404
             */
            status: number;
            /** @description Human-readable explanation specific to this occurrence. */
            detail?: string;
            /**
             * Format: uri-reference
             * @description URI reference identifying the specific occurrence.
             */
            instance?: string;
        };
    };
    responses: never;
    parameters: {
        /** @description 8-char base58 nanoid identifying the lobby (ADR-0020). */
        LobbyIdPath: components["schemas"]["LobbyId"];
        /**
         * @description UUID v7 identifying the calling player's anonymous session.
         *     Validated by the same `SessionId` value class as the WebSocket
         *     surface; non-UUID input is rejected with a 400 RFC 7807 problem.
         */
        SessionIdPath: components["schemas"]["SessionId"];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createLobby: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLobbyRequest"];
            };
        };
        responses: {
            /** @description Lobby created. Body is the freshly-minted `Lobby` resource. */
            201: {
                headers: {
                    /** @description Canonical read URL of the new lobby. */
                    Location: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lobby"];
                };
            };
            /**
             * @description Request body is malformed. RFC 7807. Variant:
             *     - `ownerSessionId` is not a UUID v7
             *       (`type` = `https://bliss.example/errors/invalid-lobby-create-request`).
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /**
             * @description Hosting requires a signed-in player (ADR-0083). An anonymous
             *     `POST /v1/lobbies` (no `__Secure-ws_session` cookie, or a
             *     session that was revoked between the cached and fresh whoami
             *     lookups) is rejected — guests get zero lobbies. Joining a
             *     lobby via link/code stays open to everyone. RFC 7807;
             *     `type` is `https://bliss.example/errors/auth-required`.
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getLobbyByCode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Six-char Crockford-style join code (`code` schema). */
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lobby found. Body matches `GET /v1/lobbies/{lobbyId}`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lobby"];
                };
            };
            /**
             * @description Path parameter `code` does not match the documented pattern.
             *     RFC 7807; `type` is `https://bliss.example/errors/invalid-lobby-code`.
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /**
             * @description No lobby carries the supplied code (typo, expired, GC'd —
             *     same v1 caveat as `lobbyId` lookup). RFC 7807;
             *     `type` is `https://bliss.example/errors/lobby-not-found`.
             */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getLobby: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 8-char base58 nanoid identifying the lobby (ADR-0020). */
                lobbyId: components["parameters"]["LobbyIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lobby found. Body is the current `Lobby` snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lobby"];
                };
            };
            /**
             * @description Path parameter `lobbyId` does not match the base58 nanoid pattern.
             *     RFC 7807; `type` is `https://bliss.example/errors/invalid-lobby-id`.
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /**
             * @description No lobby exists for the supplied id. The lobby may have never
             *     existed, or it may have been garbage-collected after the last
             *     player left (ADR-0018 §3 — in-memory v1, no durable storage).
             *     RFC 7807; `type` is `https://bliss.example/errors/lobby-not-found`.
             */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listLobbiesForSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description UUID v7 identifying the calling player's anonymous session.
                 *     Validated by the same `SessionId` value class as the WebSocket
                 *     surface; non-UUID input is rejected with a 400 RFC 7807 problem.
                 */
                sessionId: components["parameters"]["SessionIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description List of lobby summaries for this session. Empty array when the
             *     session is not a member of any lobby (never played, all lobbies
             *     garbage-collected, etc.).
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LobbySummary"][];
                };
            };
            /**
             * @description Path parameter `sessionId` is not a valid UUID. RFC 7807;
             *     `type` is `https://bliss.example/errors/invalid-session-id`.
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    deleteSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description UUID v7 identifying the calling player's anonymous session.
                 *     Validated by the same `SessionId` value class as the WebSocket
                 *     surface; non-UUID input is rejected with a 400 RFC 7807 problem.
                 */
                sessionId: components["parameters"]["SessionIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description Erasure completed. Body reports per-rule counts. All-zero is a
             *     valid success — the session had no server-side data.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteSessionResponse"];
                };
            };
            /**
             * @description Path parameter `sessionId` is not a valid UUID. RFC 7807;
             *     `type` is `https://bliss.example/errors/invalid-session-id`.
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    rebindLobbySessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    anonSessionId: components["schemas"]["SessionId"];
                };
            };
        };
        responses: {
            /** @description Rebind complete (idempotent; zero rows touched is also success). */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /**
             * @description Request body is malformed or contains an invalid field value
             *     (e.g. `anonSessionId` is not a UUID v7). RFC 7807.
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Cookie missing, expired, or rejected by identity-api. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    unbindLobbySessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    anonPseudonym: components["schemas"]["Pseudonym"];
                };
            };
        };
        responses: {
            /** @description Unbind complete (idempotent). */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /**
             * @description Request body is malformed or contains an invalid field value
             *     (e.g. `anonPseudonym` is empty or exceeds 32 characters). RFC 7807.
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Cookie missing, expired, or rejected by identity-api. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
