rootProject.name = "bliss"

include(":grid:domain")
include(":grid:application")
include(":grid:infrastructure")
include(":grid:api")
include(":grid:worker")
include(":game:domain")
include(":game:application")
include(":game:infrastructure")
include(":game:api")
include(":identity:domain")
include(":identity:application")
include(":identity:infrastructure")
include(":identity:api")
include(":survey:domain")
include(":survey:application")
include(":survey:infrastructure")
include(":survey:api")
include(":survey:worker")
include(":billing:domain")
