/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/checkout-session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start a hosted provider checkout session.
         * @description Creates a provider checkout session for the requested `tier` and
         *     returns the hosted-checkout redirect plus the success / cancel return
         *     URLs. The caller is identified by the `__Secure-ws_session` cookie;
         *     `userId` is resolved server-side and is NEVER read from the request
         *     body (no subscribe-as-another-user / IDOR, ADR-0078 threat model).
         *
         *     No card data crosses this surface — the returned `checkoutUrl` is the
         *     provider's hosted page (PCI SAQ A).
         */
        post: operations["createCheckoutSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Receive a provider webhook callback.
         * @description Public, unauthenticated-at-the-edge endpoint for provider callbacks.
         *     The body is provider-opaque on this surface: the contract models only
         *     a resource-reference `id`; the real provider payload shape is parsed in
         *     the adapter, NOT here (ADR-0078 — provider shapes never leak past
         *     infrastructure). The adapter authenticates every callback (verify the
         *     provider signature where one exists, else re-fetch the resource by
         *     `id`) before trusting it — an unauthenticated body never grants
         *     entitlement.
         *
         *     Returns 200 with an empty body on accept; the adapter processes the
         *     event asynchronously.
         */
        post: operations["receiveProviderWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/entitlement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read the caller's current entitlement.
         * @description Returns the authenticated caller's entitlement projection — the stored
         *     `tier`, subscription `status`, the current-period end (when one
         *     applies), and the resolved `capabilities`. The caller is identified by
         *     the `__Secure-ws_session` cookie; `userId` is resolved server-side.
         *
         *     Consumers gate on `capabilities`, not `tier` (ADR-0078): adding a tier
         *     is a mapping change, not a contract change.
         */
        get: operations["getEntitlement"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Request body for `POST /v1/checkout-session`. Carries only the target
         *     `tier`; `userId` is session-derived and intentionally NOT part of the
         *     body (ADR-0078 threat model).
         */
        CheckoutSessionRequest: {
            /**
             * @description Target subscription tier. Open string, not an enum: the tier set is
             *     config-driven and deliberately deferred (ADR-0078). An unknown tier
             *     is rejected with a 400.
             * @example supporter
             */
            tier: string;
        };
        /**
         * @description Response body for `POST /v1/checkout-session` on a 201. The client
         *     redirects the browser to `checkoutUrl`; the provider returns the user
         *     to `successUrl` or `cancelUrl` after the hosted-checkout flow.
         */
        CheckoutSessionResponse: {
            /**
             * Format: uri
             * @description Provider-hosted checkout page to redirect the browser to.
             * @example https://checkout.provider.example/s/abc123
             */
            checkoutUrl: string;
            /**
             * Format: uri
             * @description Return URL the provider sends the user to on success.
             * @example https://wordsparrow.io/abonnement/merci
             */
            successUrl: string;
            /**
             * Format: uri
             * @description Return URL the provider sends the user to on cancel.
             * @example https://wordsparrow.io/abonnement
             */
            cancelUrl: string;
        };
        /**
         * @description Provider webhook body. Intentionally models only the resource
         *     reference `id`; the real provider shape is parsed in the adapter, which
         *     authenticates every callback (signature verify or re-fetch-by-id)
         *     before trusting it.
         */
        WebhookEvent: {
            /**
             * @description Opaque provider resource reference. The adapter re-fetches the
             *     resource by this id to authenticate the callback rather than
             *     trusting the body.
             * @example tr_WDqYK6vllg
             */
            id: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * @description The caller's entitlement projection. `periodEnd` is always present on
         *     the wire and `null` when no current period applies (e.g. free tier or
         *     a never-subscribed user) — absence and `null` are distinct per
         *     ADR-0003 §6. Consumers gate on `capabilities`, not `tier`.
         */
        EntitlementView: {
            /**
             * @description Stored subscription tier. Open string, not an enum: the tier set is
             *     config-driven and deferred (ADR-0078).
             * @example free
             */
            tier: string;
            /**
             * @description Subscription status (e.g. active, pending_cancellation, canceled).
             *     Open string, not an enum, for the same forward-compatibility reason
             *     as `tier`.
             * @example active
             */
            status: string;
            /**
             * Format: date-time
             * @description ISO-8601 instant the current paid period ends, or `null` when no
             *     current period applies.
             * @example 2026-07-29T00:00:00Z
             */
            periodEnd: string | null;
            /**
             * @description Capabilities the caller currently holds, derived from
             *     `(status, tier)`. Consumers gate on these, never on `tier` directly
             *     (ADR-0078). Empty array when the caller holds no gated capability.
             * @example [
             *       "daily-archive",
             *       "no-ads"
             *     ]
             */
            capabilities: string[];
        };
        /**
         * @description RFC 7807 error envelope (ADR-0003 §6). Additional members per
         *     RFC 7807 §3.2 may appear; clients tolerate them.
         */
        Problem: {
            /**
             * Format: uri
             * @description Stable URI for the error class. Clients route on `type`, never on
             *     `title` or `detail`.
             * @example https://bliss.example/errors/auth-required
             */
            type: string;
            /**
             * @description Short, human-readable summary of the error class.
             * @example Authentication required
             */
            title: string;
            /**
             * @description HTTP status code, repeated for clients that lose it.
             * @example 401
             */
            status: number;
            /** @description Human-readable explanation specific to this occurrence. */
            detail?: string;
            /**
             * Format: uri-reference
             * @description URI reference identifying the specific occurrence.
             */
            instance?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createCheckoutSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckoutSessionRequest"];
            };
        };
        responses: {
            /**
             * @description Checkout session created. Body carries the hosted-checkout URL the
             *     client redirects to, plus the success and cancel return URLs.
             */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutSessionResponse"];
                };
            };
            /**
             * @description Request is malformed — missing or unknown `tier`. RFC 7807 body;
             *     `type` is `https://bliss.example/errors/invalid-checkout-request`.
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /**
             * @description No valid `__Secure-ws_session` cookie. The session is missing,
             *     unparseable, or revoked. RFC 7807;
             *     `type` is `https://bliss.example/errors/auth-required`.
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    receiveProviderWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebhookEvent"];
            };
        };
        responses: {
            /**
             * @description Callback accepted for processing. Empty body. The provider treats
             *     any 2xx as delivered; authentication and parsing happen in the
             *     adapter behind this acknowledgement.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /**
             * @description Body is missing or unparseable (no resource reference `id`).
             *     RFC 7807; `type` is
             *     `https://bliss.example/errors/invalid-webhook-body`.
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getEntitlement: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Entitlement resolved for the authenticated caller. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntitlementView"];
                };
            };
            /**
             * @description No valid `__Secure-ws_session` cookie. RFC 7807;
             *     `type` is `https://bliss.example/errors/auth-required`.
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
