#!/usr/bin/env python3
"""Merge surface_clues.csv into the runtime words-fr.csv consumed by the API.

For each row in words-fr.csv whose surface (word column) has a clue in
surface_clues.csv (validator-ok and filter_score >= threshold), replace
the placeholder `clue` field. For grammalecte rows with no shipped clue
the clue field is reset to the empty string (empty-clue convention); the
loader (CsvWordRepository) silently drops them at startup. Curated
source=bliss rows are left unchanged.

Source/license columns describe the WORD provenance (grammalecte
morphology — MPL-2.0); the clue text itself is LoRA-generated by us
from CC0 training data, no DBnary. We preserve the existing source
and source_license fields and don't add per-field provenance.
"""
from __future__ import annotations
import argparse, csv, shutil, sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(REPO / "scripts" / "clue_generation"))
from apply_clue_overrides import DEFAULT_OVERRIDES, load_overrides  # noqa: E402


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--wordlist", type=Path,
                   default=REPO / "grid/api/src/main/resources/words/words-fr.csv")
    p.add_argument("--shipped", type=Path,
                   default=REPO / "data/eval/production/surface_clues.csv")
    p.add_argument("--dropped", type=Path,
                   default=REPO / "data/eval/production/surface_clues_dropped.csv")
    p.add_argument("--include-dropped", action="store_true",
                   help="also use lower-confidence (dropped) surface clues")
    p.add_argument("--min-score", type=float, default=0.0,
                   help="minimum filter_score; clues below are skipped")
    p.add_argument("--backup", type=Path,
                   default=REPO / "/tmp/words-fr.backup.csv")
    p.add_argument("--overrides", type=Path, default=DEFAULT_OVERRIDES)
    args = p.parse_args()

    def keep(r: dict) -> bool:
        try:
            return float(r.get("filter_score", 0) or 0) >= args.min_score
        except ValueError:
            return False

    # surface_lower -> clue_text. The compact column has been retired
    # (MAX_CLUE_CHARS = 25 makes the single/stacked distinction moot).
    surface_clue: dict[str, str] = {}
    with args.shipped.open(encoding="utf-8", newline="") as f:
        for r in csv.DictReader(f):
            if keep(r):
                surface_clue[r["surface"].lower()] = r["clue"]
    if args.include_dropped:
        with args.dropped.open(encoding="utf-8", newline="") as f:
            for r in csv.DictReader(f):
                if keep(r):
                    surface_clue.setdefault(r["surface"].lower(), r["clue"])
    print(f"surface clues available (score >= {args.min_score}): {len(surface_clue)}")

    # Backup, then rewrite in place.
    shutil.copy2(args.wordlist, args.backup)
    with args.wordlist.open(encoding="utf-8", newline="") as f:
        rows = list(csv.DictReader(f))
        fieldnames = list(rows[0].keys())

    # Drop the `compact` column from the runtime CSV if it's still there
    # from an older merge run. The column was retired alongside the
    # MAX_CLUE_CHARS = 25 cap; it no longer serves a purpose.
    if "compact" in fieldnames:
        fieldnames.remove("compact")
        for r in rows:
            r.pop("compact", None)

    updated = 0
    reset = 0
    for r in rows:
        word = r.get("word", "").strip()
        clue = surface_clue.get(word.lower())
        if clue is not None:
            r["clue"] = clue
            updated += 1
        elif r.get("source") == "grammalecte":
            # Blank the clue for rows whose word came from the
            # LoRA-eligible grammalecte universe but have no shipped
            # clue. Blank-clue rows are filtered out of the usable
            # corpus by the loader (CsvWordRepository.toWordWithFreq
            # returns null on blank clue), so they're invisible to the
            # grid generator. Without this scrub, surfaces dropped by
            # a later iter (filter_score below threshold) silently
            # retain clues from earlier iters — the leak that surfaced
            # compliqué → "Ajouté de la difficulté" after v7 dropped
            # compliquer's lemma clue.
            #
            # source=bliss rows (curated short-fr / roman numerals)
            # are left alone: they hold hand-authored CC0 clues that
            # don't go through the LoRA pipeline.
            if r.get("clue"):
                r["clue"] = ""
                reset += 1

    # Curated overrides win, applied last, so hand-authored fixes for recurring English-sense homograph leaks (e.g. `pain`/`cane`) survive the next `run_production.sh` regeneration.
    overrides = load_overrides(args.overrides)
    overridden = 0
    for r in rows:
        new = overrides.get(r.get("word", "").strip().lower())
        if new is not None and r.get("clue") != new:
            r["clue"] = new
            overridden += 1

    with args.wordlist.open("w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fieldnames, lineterminator="\n")
        w.writeheader()
        for r in rows:
            w.writerow({k: r.get(k, "") for k in fieldnames})

    pct = updated / len(rows) * 100
    print(f"updated {updated}/{len(rows)} rows ({pct:.1f}%)")
    print(f"blanked to empty-clue convention (stale clue scrub): {reset}")
    print(f"curated overrides applied: {overridden}")
    print(f"backup: {args.backup}")


if __name__ == "__main__":
    main()
