/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/campaign/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Return the current campaign and its lock state.
         * @description Returns the open campaign if one exists, otherwise the most recently
         *     closed campaign. The frontend treats a non-null `closedAt` as "the
         *     sondage is locked": render the LockBanner and disable verdict /
         *     Corriger controls. Polled on mount and visibilitychange; no
         *     long-poll, no WebSocket. 503 only when no campaign has ever existed
         *     (operator error caught by smoke tests).
         */
        get: operations["getCurrentCampaign"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/items/next": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the next unrated item for the caller.
         * @description Pulls one survey item the caller has not yet rated, applying tier-
         *     stratified weighted sampling and K-coverage prioritisation. Auth
         *     optional: signed-in callers are dedup'd server-side; anonymous
         *     callers may provide `excluded` to perform client-side dedup.
         */
        get: operations["getNextItem"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/items/{itemId}/rating": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit a rating for an item.
         * @description Server assigns `submittedAs` based on session presence. For auth
         *     callers, the partial unique index on (itemId, userId) makes this
         *     idempotent — a repeat submission returns 409 with the existing
         *     rating. For anon callers, every submit creates a new row (no
         *     server-side dedup). Anonymous callers including a `correctif` or
         *     any meta annotation (`targetCategories`, `targetSense`,
         *     `isMultisense`, `subTags`) are rejected with 401 — corpus
         *     contributions and sense/category annotation both require sign-in.
         */
        post: operations["submitRating"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/items/pairs/next": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the next unrated pair (same mot) for pairwise rating.
         * @description Pulls two distinct survey items for the same `mot`, both unrated by
         *     the caller. Same auth/dedup rules as `/v1/items/next`. Returns 204
         *     when no mot has at least two unrated candidates available.
         */
        get: operations["getNextPair"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ratings/pair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit a pairwise verdict on two items for the same mot.
         * @description Records a pairwise verdict. Routing depends on whether the verdict
         *     expresses a preference or a tied absolute judgment:
         *       - LEFT_WINS / RIGHT_WINS → 1 row in `pair_ratings` (consumed by
         *         DPO pair builder directly as chosen/rejected).
         *       - BOTH_GOOD → 2 rows in `ratings` (qualite=5 each).
         *       - BOTH_BAD  → 2 rows in `ratings` (qualite=1 each).
         *       - SKIP      → no writes; client advances.
         *     `pair_ratings` stays a strict preference table — every row is a
         *     usable DPO pair. Absolute judgments accumulate in `ratings`
         *     alongside the binary-mode submissions.
         */
        post: operations["submitPairRating"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/actions/undo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Undo the action identified by a capability token.
         * @description Reverses every write a submit produced, using the capability token
         *     returned as `undoToken`. The token travels in the body, never the URL.
         *     Anon actions authorize on possession; authed actions additionally bind
         *     to the session user. Undoable while the campaign is open and for an 8 s
         *     close grace; 410 once the grace elapses.
         */
        post: operations["undoAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Caller's rating progress. */
        get: operations["getMyProgress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/contributions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Caller's proposed-clue contributions. */
        get: operations["getMyContributions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update caller's survey preferences.
         * @description Currently only `deleteProposedOnErasure`. Updates `proposedBy.optedOut` for all existing contributions and applies to future ones.
         */
        patch: operations["patchMyPreferences"];
        trace?: never;
    };
    "/v1/lemma-meta/{mot}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Per-lemma autocomplete source for sense glosses and sub-tags.
         * @description Aggregates the distinct sense glosses and sub-tags observed across
         *     past ratings of this lemma. Both `priorSenses` and `priorSubTags`
         *     are machine-grown from rating history — there is no separate
         *     curation surface. Powers the rating-card autocomplete dropdowns.
         *     Open auth (no PII, vocabulary-only). Both arrays are always
         *     returned — empty when the lemma has not been rated yet.
         */
        get: operations["getLemmaMeta"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness + readiness. */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description A rating-collection lifecycle window. At most one campaign is "open"
         *     (closedAt is null) at any time. When the current campaign is closed
         *     and no successor has been opened, rating POSTs return 423.
         */
        Campaign: {
            /** Format: uuid */
            campaignId: string;
            /** @description Human label tying this campaign to a downstream training batch (e.g. `round-7`). */
            batchLabel: string;
            /** Format: date-time */
            openedAt: string;
            /**
             * Format: date-time
             * @description Null while the campaign is collecting; non-null after the maintainer closes it.
             */
            closedAt: string | null;
        };
        Item: {
            /** Format: uuid */
            itemId: string;
            mot: string;
            definition: string;
            pos: components["schemas"]["Pos"];
            categorie: components["schemas"]["Categorie"];
            style: components["schemas"]["Style"];
            forceClaimed: number;
            longueur: number;
            /** @enum {string} */
            tier: "high" | "mid" | "low" | "excluded";
            isCalibration: boolean;
        };
        /**
         * @description Part of speech of the clued answer. `polyvalent` marks a clue with
         *     multiple valid readings — sense-only (e.g. ARGENT money/colour, both
         *     noun) or cross-POS (noun + adjective) — collapsed into one bucket;
         *     distinct from `autre` (POS unknown/not applicable).
         * @enum {string}
         */
        Pos: "verbe_infinitif" | "participe_passe" | "participe_present" | "nom_commun" | "nom_propre" | "adjectif" | "adverbe" | "interjection" | "mot_outil" | "sigle_abreviation" | "polyvalent" | "autre";
        /**
         * @description High-level answer class. 18 broad classes + `autre`; one word each,
         *     scannable, spanning nouns, verbs (`action`) and adjectives
         *     (`qualificatif`). All granularity lives in free-form sub-tags, not
         *     here.
         * @enum {string}
         */
        Categorie: "personne" | "faune_flore" | "geographie" | "meteo" | "objet" | "nourriture" | "corps" | "culture" | "histoire" | "jeu" | "sport" | "religion" | "societe" | "science" | "conceptuel" | "langue" | "action" | "qualificatif" | "autre";
        /** @enum {string} */
        Style: "definition_directe" | "periphrase" | "metonymie" | "fonction_role" | "calembour" | "culturel" | "cryptique" | "cryptique_morphologique" | "technique";
        ItemPair: {
            mot: string;
            left: components["schemas"]["Item"];
            right: components["schemas"]["Item"];
        };
        /** @enum {string} */
        PairVerdict: "LEFT_WINS" | "RIGHT_WINS" | "BOTH_GOOD" | "BOTH_BAD" | "SKIP";
        PairRatingRequest: {
            /** Format: uuid */
            leftItemId: string;
            /** Format: uuid */
            rightItemId: string;
            verdict: components["schemas"]["PairVerdict"];
            difficulte: number;
            latencyMs: number;
        };
        RatingRequest: {
            qualite: number;
            difficulte: number;
            /** @enum {string} */
            flag?: "hors_sujet" | "auto_reference" | "erreur_sens" | "autre";
            /**
             * @description Clue correction. Authenticated callers only. When `pos` is set and
             *     `text` equals the original clue, the original item's POS is patched
             *     in place; when `text` differs, a new rater-proposed item carries the
             *     corrected text and `pos` (defaulting to the parent's POS when absent).
             */
            correctif?: {
                text: string;
                style: components["schemas"]["Style"];
                pos?: components["schemas"]["Pos"];
            };
            /**
             * @description High-level answer classes the rater assigns to this definition.
             *     An editable multi-select, pre-filled client-side from the item's
             *     single machine `categorie` prior but freely overridden. Any
             *     authenticated rater may set it; anonymous submissions including
             *     this field return 401. When several raters annotate the same
             *     definition, maintainer ratings take precedence on resolution.
             *     Omitted when the rater does not annotate categories.
             */
            targetCategories?: components["schemas"]["Categorie"][];
            /**
             * @description Single freeform sense gloss this clue targets. Must not repeat
             *     the lemma; server soft-normalizes for autocomplete dedup, stores
             *     the original spelling. Omitted when sense is not annotated
             *     or `isMultisense` is true. Authenticated callers only.
             */
            targetSense?: string;
            /**
             * @description Calembour marker: the clue deliberately plays on several senses
             *     at once. When true, `targetSense` is optional — the senses are
             *     not enumerated. Authenticated callers only.
             * @default false
             */
            isMultisense: boolean;
            /**
             * @description Free-form sub-domain refinement tags for this definition — finer
             *     than `targetCategories` (e.g. felin, capitale, note de musique).
             *     Per-rating. Server soft-normalizes for autocomplete dedup, stores
             *     the original spelling. Authenticated callers only. Omitted when
             *     not annotated.
             */
            subTags?: string[];
            latencyMs: number;
        };
        UndoActionRequest: {
            /** @description The capability token returned as undoToken by the submit response. */
            token: string;
        };
        RatingResponse: {
            /** Format: uuid */
            ratingId: string;
            /** Format: uuid */
            itemId: string;
            /** @enum {string} */
            submittedAs: "auth" | "anon";
            /**
             * Format: uuid
             * @description UUID of the queued correctif item; null when no correctif was submitted.
             */
            proposedItemId: string | null;
            /**
             * Format: uuid
             * @description Campaign whose lifecycle window this rating landed in. Stamped by the server at insert time.
             */
            campaignId: string;
            /** @description Capability token for undoing this action. Non-null on 201 (fresh action); null on 409 (idempotent re-rate). Present it in the body of POST /v1/actions/undo. */
            undoToken: string | null;
        };
        PairRatingResponse: {
            /**
             * Format: uuid
             * @description Campaign whose lifecycle window this pair verdict landed in. Stamped by the server at insert time.
             */
            campaignId: string;
            /** @description Capability token for undoing this pair action. Non-null on 201. Present it in the body of POST /v1/actions/undo. */
            undoToken: string;
        };
        CorrectifRejection: {
            /** Format: uri */
            type: string;
            title: string;
            status: number;
            filterId: number;
            reason: string;
        };
        ProgressResponse: {
            itemsRated: number;
            /**
             * Format: float
             * @description Agreement ratio with calibration items; null until the first calibration rating.
             */
            calibrationAgreement: number | null;
            /**
             * Format: date-time
             * @description ISO-8601 timestamp of the most recent rating; null until the first submission.
             */
            lastRatedAt: string | null;
        };
        ContributionItem: {
            /** Format: uuid */
            itemId: string;
            mot: string;
            definition: string;
            pos: components["schemas"]["Pos"];
            categorie: components["schemas"]["Categorie"];
            style: components["schemas"]["Style"];
            optedOut: boolean;
            kCoverage: number;
            /** Format: date-time */
            createdAt: string;
        };
        PreferencesPatch: {
            deleteProposedOnErasure: boolean;
        };
        /**
         * @description Per-lemma autocomplete payload. Both arrays are always present,
         *     empty when the lemma has no history. Both `priorSenses` and
         *     `priorSubTags` are machine-grown by aggregating the distinct values
         *     observed across past ratings of this lemma; there is no separate
         *     curation surface.
         */
        LemmaMeta: {
            /** @description Distinct sense glosses observed in past ratings of this lemma. Ordered most-recent first. */
            priorSenses: string[];
            /** @description Distinct sub-domain tags observed in past ratings of this lemma. Ordered most-recent first. */
            priorSubTags: string[];
        };
        ProblemDetails: {
            /** Format: uri */
            type: string;
            title: string;
            status: number;
            detail?: string;
        };
    };
    responses: {
        /** @description RFC 7807 problem details. */
        ProblemDetails: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getCurrentCampaign: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current campaign. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Campaign"];
                };
            };
            403: components["responses"]["ProblemDetails"];
            503: components["responses"]["ProblemDetails"];
        };
    };
    getNextItem: {
        parameters: {
            query?: {
                /** @description Comma-separated list of `itemId`s the anonymous caller has already rated locally. Ignored when the caller is authenticated. */
                excluded?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Next item. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Item"];
                };
            };
            /** @description Pool exhausted — no unrated items remain for this caller. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["ProblemDetails"];
            503: components["responses"]["ProblemDetails"];
        };
    };
    submitRating: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RatingRequest"];
            };
        };
        responses: {
            /** @description Rating accepted. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RatingResponse"];
                };
            };
            400: components["responses"]["ProblemDetails"];
            401: components["responses"]["ProblemDetails"];
            403: components["responses"]["ProblemDetails"];
            404: components["responses"]["ProblemDetails"];
            /** @description Auth caller already rated this item. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RatingResponse"];
                };
            };
            /** @description Correctif rejected by style-guide filters (1–7). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["CorrectifRejection"];
                };
            };
            /** @description No open campaign — the sondage is locked. */
            423: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getNextPair: {
        parameters: {
            query?: {
                /** @description Comma-separated list of `itemId`s the anonymous caller has already rated locally. Ignored when the caller is authenticated. */
                excluded?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Next pair. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemPair"];
                };
            };
            /** @description No mot has two unrated candidates available. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["ProblemDetails"];
            503: components["responses"]["ProblemDetails"];
        };
    };
    submitPairRating: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PairRatingRequest"];
            };
        };
        responses: {
            /** @description Pair verdict recorded — at least one row written. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PairRatingResponse"];
                };
            };
            /** @description SKIP verdict — no rows written, no body returned. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["ProblemDetails"];
            403: components["responses"]["ProblemDetails"];
            404: components["responses"]["ProblemDetails"];
            409: components["responses"]["ProblemDetails"];
            /** @description No open campaign — the sondage is locked. */
            423: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    undoAction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UndoActionRequest"];
            };
        };
        responses: {
            /** @description Action reversed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["ProblemDetails"];
            /** @description Token unknown, not yours, or already undone. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Campaign-close grace window has elapsed. */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getMyProgress: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Progress snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressResponse"];
                };
            };
            401: components["responses"]["ProblemDetails"];
            403: components["responses"]["ProblemDetails"];
        };
    };
    getMyContributions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of items the caller proposed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContributionItem"][];
                };
            };
            401: components["responses"]["ProblemDetails"];
            403: components["responses"]["ProblemDetails"];
        };
    };
    patchMyPreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreferencesPatch"];
            };
        };
        responses: {
            /** @description Preferences updated. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["ProblemDetails"];
            401: components["responses"]["ProblemDetails"];
            403: components["responses"]["ProblemDetails"];
        };
    };
    getLemmaMeta: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Lemma surface form (the French word to look up). Matched as stored — no normalization on read. */
                mot: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lemma meta (possibly empty). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LemmaMeta"];
                };
            };
            403: components["responses"]["ProblemDetails"];
            503: components["responses"]["ProblemDetails"];
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Database or NATS unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
