/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/auth/{provider}/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Start an OIDC sign-in flow.
         * @description Validates `provider` and `return_to`, creates a state cookie for CSRF
         *     protection, then redirects the browser to the IdP authorise endpoint.
         */
        get: operations["beginLogin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Google OIDC callback (GET, query string).
         * @description Google posts `code` and `state` as query parameters. Verifies state,
         *     exchanges the code for an id_token, upserts the player, issues the
         *     session cookie, and redirects to `return_to`.
         */
        get: operations["googleCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/apple/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apple OIDC callback (POST, form-encoded body — Apple uses response_mode=form_post).
         * @description Apple uses `response_mode=form_post`, delivering `code`, `state`, and
         *     optionally a `user` JSON payload in the form body. Verifies state,
         *     exchanges the code for an id_token, upserts the player, issues the
         *     session cookie, and redirects to `return_to`.
         */
        post: operations["appleCallback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/whoami": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Resolve the current session cookie to a user.
         * @description Used by grid-api and game-api for downstream auth. Returns minimal
         *     identity (userId + displayName + role) without PII. Returns 401 if no valid
         *     session cookie is present.
         */
        get: operations["whoAmI"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke the current session and clear the cookie.
         * @description Deletes the server-side session record and sets a clearing Set-Cookie
         *     header. Safe to call even when no session exists (idempotent on the
         *     client side; returns 401 only when the cookie is absent).
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Return the current user.
         * @description Returns the full user profile for the authenticated player, including
         *     linked providers and account metadata.
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        /**
         * Hard-delete the user; cascades to grid/game via UserDeleted event (RGPD Article 17).
         * @description Permanently deletes the player account and publishes a `UserDeleted`
         *     domain event so that grid-api and game-api can wipe their user-scoped
         *     rows. Sets a clearing Set-Cookie. Per ADR-0045 §4 (data minimization),
         *     no soft-delete — the row is gone immediately.
         */
        delete: operations["deleteMe"];
        options?: never;
        head?: never;
        /**
         * Update display name and/or email-opt-in.
         * @description Partial update — only the fields present in the body are changed.
         *     `displayName` is deduplicated by appending a numeric suffix if already
         *     taken (per ADR-0045 §2).
         */
        patch: operations["updateMe"];
        trace?: never;
    };
    "/v1/users/me/providers/{provider}/link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Begin an OIDC flow that links another provider to the current user.
         * @description Generates an IdP authorise URL that, when followed by the browser,
         *     will call the corresponding callback and attach the new provider to the
         *     existing account. Returns the URL for the frontend to navigate to; it
         *     does not redirect server-side.
         */
        post: operations["linkProvider"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/me/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Batch-pull all of the current user's solo puzzle progress.
         * @description Returns every stored puzzle-progress entry for the authenticated
         *     player in one call — the grilles archive needs the full set on load,
         *     not one round-trip per puzzle. Returns an empty `items` array when the
         *     player has stored nothing; never 404.
         */
        get: operations["listProgress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/me/progress/{puzzleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pull the current user's progress for one puzzle.
         * @description Returns the stored progress entry for one puzzle, or 404 when the
         *     player has no row for it.
         */
        get: operations["getProgress"];
        /**
         * Push the current user's progress for one puzzle.
         * @description Upserts the player's progress for one puzzle and returns the
         *     server-stamped `updatedAt`. The server stores `payload` verbatim and
         *     never parses it (ADR-0075). When `baseUpdatedAt` is present and does
         *     not match the row's current `updatedAt`, the push is rejected with 409
         *     so the client can re-pull, re-merge, and re-push (optimistic
         *     concurrency).
         */
        put: operations["putProgress"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        User: {
            /** Format: uuid */
            id: string;
            displayName: string;
            providers: components["schemas"]["LinkedProvider"][];
            /** Format: date-time */
            createdAt: string;
            /** @enum {string} */
            role: "player" | "maintainer";
        };
        LinkedProvider: {
            /** @enum {string} */
            provider: "google" | "apple";
            /** Format: date-time */
            linkedAt: string;
            emailOptIn: boolean;
        };
        UserUpdate: {
            displayName?: string;
            emailOptIn?: boolean;
        };
        WhoAmIResponse: {
            /** Format: uuid */
            userId: string;
            displayName: string;
            /** @enum {string} */
            role: "player" | "maintainer";
        };
        BeginLinkResponse: {
            /** Format: uri */
            authorizeUrl: string;
        };
        ProgressEntry: {
            /** Format: uuid */
            puzzleId: string;
            payload: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            updatedAt: string;
        };
        ProgressList: {
            items: components["schemas"]["ProgressEntry"][];
        };
        ProgressUpdate: {
            payload: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            baseUpdatedAt?: string;
        };
        ProgressWriteResult: {
            /** Format: date-time */
            updatedAt: string;
        };
        ProblemDetails: {
            /** Format: uri */
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
        };
    };
    responses: {
        /** @description RFC 7807 problem+json */
        ProblemDetails: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: {
        /** @description OIDC provider identifier. Currently `google` or `apple`. */
        ProviderPath: "google" | "apple";
        /** @description UUID v7 identifier of the puzzle the progress is stored under. */
        PuzzleIdPath: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    beginLogin: {
        parameters: {
            query: {
                /** @description URL to redirect to after a successful or failed sign-in. Must be under the app origin. */
                return_to: string;
            };
            header?: never;
            path: {
                /** @description OIDC provider identifier. Currently `google` or `apple`. */
                provider: components["parameters"]["ProviderPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to the IdP authorise endpoint. */
            302: {
                headers: {
                    "Set-Cookie"?: string;
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["ProblemDetails"];
        };
    };
    googleCallback: {
        parameters: {
            query: {
                /** @description Authorization code returned by Google. */
                code: string;
                /** @description Opaque CSRF state value that must match the state cookie. */
                state: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to `return_to`. Sets the session cookie if sign-in succeeded. */
            302: {
                headers: {
                    "Set-Cookie"?: string;
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["ProblemDetails"];
            409: components["responses"]["ProblemDetails"];
            500: components["responses"]["ProblemDetails"];
            503: components["responses"]["ProblemDetails"];
        };
    };
    appleCallback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": {
                    /** @description Authorization code returned by Apple. */
                    code: string;
                    /** @description Opaque CSRF state value that must match the state cookie. */
                    state: string;
                    /** @description Apple's name JSON, only present on first sign-in. Ignored by this API. */
                    user?: string;
                };
            };
        };
        responses: {
            /** @description Redirect to `return_to`. Sets the session cookie if sign-in succeeded. */
            302: {
                headers: {
                    "Set-Cookie"?: string;
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["ProblemDetails"];
            409: components["responses"]["ProblemDetails"];
            500: components["responses"]["ProblemDetails"];
            503: components["responses"]["ProblemDetails"];
        };
    };
    whoAmI: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed in. Returns the minimal identity for the session. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhoAmIResponse"];
                };
            };
            401: components["responses"]["ProblemDetails"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out. Response sets a clearing Set-Cookie. */
            204: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["ProblemDetails"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The authenticated user's profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["ProblemDetails"];
        };
    };
    deleteMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted; response sets a clearing Set-Cookie. */
            204: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["ProblemDetails"];
            503: components["responses"]["ProblemDetails"];
        };
    };
    updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description The updated user profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["ProblemDetails"];
            401: components["responses"]["ProblemDetails"];
        };
    };
    linkProvider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description OIDC provider identifier. Currently `google` or `apple`. */
                provider: components["parameters"]["ProviderPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uri */
                    returnTo: string;
                };
            };
        };
        responses: {
            /** @description Returns the IdP authorise URL for the frontend to navigate the browser to. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BeginLinkResponse"];
                };
            };
            400: components["responses"]["ProblemDetails"];
            401: components["responses"]["ProblemDetails"];
        };
    };
    listProgress: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The authenticated user's full set of progress entries. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressList"];
                };
            };
            401: components["responses"]["ProblemDetails"];
        };
    };
    getProgress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID v7 identifier of the puzzle the progress is stored under. */
                puzzleId: components["parameters"]["PuzzleIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The stored progress entry for the requested puzzle. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressEntry"];
                };
            };
            401: components["responses"]["ProblemDetails"];
            404: components["responses"]["ProblemDetails"];
        };
    };
    putProgress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID v7 identifier of the puzzle the progress is stored under. */
                puzzleId: components["parameters"]["PuzzleIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProgressUpdate"];
            };
        };
        responses: {
            /** @description Stored. Returns the server-stamped write time. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressWriteResult"];
                };
            };
            400: components["responses"]["ProblemDetails"];
            401: components["responses"]["ProblemDetails"];
            409: components["responses"]["ProblemDetails"];
            413: components["responses"]["ProblemDetails"];
        };
    };
}
