package com.bliss.grid.infrastructure.persistence

import com.bliss.grid.domain.generation.WordRepository
import com.bliss.grid.domain.model.Word
import org.apache.commons.csv.CSVFormat
import org.apache.commons.csv.CSVParser
import org.apache.commons.csv.CSVRecord
import java.io.InputStreamReader
import java.nio.charset.StandardCharsets
import java.text.Normalizer

/**
 * Classpath-backed [WordRepository] reading the committed CSV corpus
 * (ADR-0013 §8 — CSV as source of truth).
 *
 * Production grid-api ships its words as
 * `grid/infrastructure/src/main/resources/words/words-<lang>.csv`, generated by the
 * worker's `export-words` sub-command from the local-dev `words` table after
 * an operator review pass. The CSV is the single source of truth in
 * production: there is no DB read path, no LLM call on the request hot path,
 * no autonomous remote dependency. The dataset is auditable, deterministic,
 * and deploys with the image.
 *
 * CSV columns (header row required, in the listed order):
 * `word, language, length, frequency, difficulty, clue, source, source_license`
 * with an optional trailing `lemma` column. When `lemma` is present the
 * generator dedupes inflected forms of the same headword (e.g. "court" +
 * "courait") within a single grid; when absent, lemma defaults to the word
 * itself and dedup degenerates to surface-form-only (legacy behavior).
 *
 * Rows with a blank `clue` are silently dropped from the usable corpus —
 * they represent surfaces the current clue-generation iteration has not
 * yet covered. The `export-words` pipeline sets these to empty (empty-clue
 * convention) rather than a placeholder; `toWordWithFreq` returns `null`
 * and the grid generator never sees unclueable words.
 *
 * No frequency floor is applied at load time. The Python build pipeline
 * (lemma-anchored admission in `scripts/clue_generation/`) is the
 * gatekeeper for what gets into `words-fr.csv`: a surface ships only if
 * its lemma already has at least one row in the corpus and its
 * grammalecte tag isn't in the obscure-form blocklist (passé simple,
 * subjonctif imparfait, conditionnel 1pl/2pl). The blank-clue drop
 * remains the runtime fallback for any surface the inflater couldn't
 * upgrade past the `clue == word` placeholder.
 */
class CsvWordRepository(
    words: List<Word>,
) : WordRepository {
    private val byLength: Map<Int, List<Word>> = words.groupBy { it.text.length }

    /**
     * Position-letter index: `byLengthPosLetter[length][position][char] = words containing
     * that char at that position`. Built once at construction; pattern matching becomes a
     * small-set intersection instead of an O(N) linear scan, which is the difference between
     * milliseconds and microseconds when the CSP solver issues thousands of pattern lookups
     * per puzzle generation.
     *
     * Storage: for each length L we keep an array of L maps (one per position), each mapping
     * char → list of words. Total memory ≈ |words| × avg-length pointers ≈ a few MB on the
     * full corpus — negligible compared to the CSV itself sitting in the heap.
     */
    private val byLengthPosLetter: Map<Int, Array<Map<Char, List<Word>>>> =
        byLength.mapValues { (length, wordsOfLen) ->
            Array(length) { pos ->
                wordsOfLen.groupBy { it.text[pos] }
            }
        }

    /**
     * Set of every surface form and lemma in the corpus, folded to grid-cell
     * uppercase ASCII (the same form as `Word.text` / `Word.lemma`). Backs
     * [containsLemma]'s O(1) lookup. Memory: ~2× word count strings; tiny
     * compared to the corpus already in heap.
     */
    private val knownTokens: Set<String> =
        words.flatMap { setOf(it.text, it.lemma) }.toSet()

    override fun findByLength(length: Int): List<Word> = byLength[length].orEmpty()

    override fun countByLength(length: Int): Int = byLength[length]?.size ?: 0

    override fun lettersAtPosition(
        length: Int,
        position: Int,
    ): Set<Char> {
        val posIndex = byLengthPosLetter[length] ?: return emptySet()
        if (position !in posIndex.indices) return emptySet()
        return posIndex[position].keys
    }

    override fun findByLengthAndPattern(
        length: Int,
        pattern: Map<Int, Char>,
    ): List<Word> {
        if (pattern.isEmpty()) return findByLength(length)
        val posIndex = byLengthPosLetter[length] ?: return emptyList()
        // Validate positions and short-circuit on any unsatisfiable constraint.
        val candidateLists =
            pattern.map { (i, ch) ->
                if (i !in 0 until length) return emptyList()
                posIndex[i][ch] ?: return emptyList()
            }
        // Intersect smallest-first — typical patterns have a constraint that pins down
        // the candidate set to <100 words, so we never iterate the long axis.
        val sorted = candidateLists.sortedBy { it.size }
        if (sorted.size == 1) return sorted[0]
        val seed = sorted[0].toHashSet()
        for (i in 1 until sorted.size) seed.retainAll(sorted[i].toHashSet())
        // Preserve the input ordering of `byLength[length]` so frequency-based ordering
        // (when present) is respected by callers that iterate in order.
        return sorted[0].filter { it in seed }
    }

    override fun containsLemma(text: String): Boolean {
        if (text.isBlank()) return false
        val folded = foldToAscii(text)
        if (folded.isEmpty() || folded.any { it !in 'A'..'Z' }) return false
        return folded in knownTokens
    }

    companion object {
        private const val FRENCH_RESOURCE_PATH = "/words/words-fr.csv"

        /**
         * Per-theme overlay files shipped alongside the main French corpus.
         * Each entry pairs a [com.bliss.grid.domain.generation.Themes]
         * constant with a classpath path. The repository merges these at
         * load time so curated themed entries propagate to runtime without
         * requiring a separate pipeline step. Missing files are tolerated
         * (silently skipped) so a partial deploy doesn't fail the load.
         */
        private val FRENCH_THEMED_OVERLAY_PATHS: List<Pair<String, String>> =
            listOf(
                com.bliss.grid.domain.generation.Themes.ROMAN to "/words/themed/roman.csv",
                com.bliss.grid.domain.generation.Themes.CHEM to "/words/themed/chem.csv",
                com.bliss.grid.domain.generation.Themes.ABBREV to "/words/themed/abbrev.csv",
                com.bliss.grid.domain.generation.Themes.COMPASS to "/words/themed/compass.csv",
                com.bliss.grid.domain.generation.Themes.COUNTRY to "/words/themed/country.csv",
                com.bliss.grid.domain.generation.Themes.NOTE to "/words/themed/note.csv",
                com.bliss.grid.domain.generation.Themes.UNIT to "/words/themed/unit.csv",
                com.bliss.grid.domain.generation.Themes.INTERJECTION to "/words/themed/interjection.csv",
                com.bliss.grid.domain.generation.Themes.GREEK to "/words/themed/greek.csv",
                com.bliss.grid.domain.generation.Themes.SIGLE to "/words/themed/sigle.csv",
            )

        private val REQUIRED_HEADERS =
            listOf("word", "language", "length", "frequency", "difficulty", "clue", "source", "source_license")
        private const val OPTIONAL_LEMMA_HEADER = "lemma"
        private const val OPTIONAL_THEME_HEADER = "theme"

        /**
         * Loads the bundled French CSV corpus from the JVM classpath.
         *
         * Fails fast at startup if the file is missing or the header row is
         * malformed.
         */
        fun frenchFromClasspath(): CsvWordRepository = fromClasspath(FRENCH_RESOURCE_PATH, FRENCH_THEMED_OVERLAY_PATHS)

        fun fromClasspath(
            path: String,
            themedOverlayPaths: List<Pair<String, String>> = emptyList(),
        ): CsvWordRepository {
            // Load theme overlays first so we can apply them while parsing the
            // main CSV. Each overlay is `(theme, classpath-path)` — the CSV
            // there carries the same schema as the main words file, but every
            // word listed gets stamped with the overlay's theme. Curated rows
            // are the source of truth; a word in two overlays (e.g. AG in
            // chem + sigle) keeps a themed clue from each (see loadThemeOverlays).
            val overlay = loadThemeOverlays(themedOverlayPaths)

            val stream =
                CsvWordRepository::class.java.getResourceAsStream(path)
                    ?: error("Word CSV not found on classpath: $path")
            return stream.use { input ->
                InputStreamReader(input, StandardCharsets.UTF_8).use { reader ->
                    // setHeader() with no args = auto-detect from the first CSV row,
                    // which we then validate against REQUIRED_HEADERS — this catches
                    // hand-edited corruption that reorders or renames columns.
                    val format =
                        CSVFormat.RFC4180
                            .builder()
                            .setHeader()
                            .setSkipHeaderRecord(true)
                            .build()
                    CSVParser.parse(reader, format).use { parser ->
                        validateHeader(parser.headerNames, path)
                        // Skip rows whose word doesn't fully fold to A-Z (script symbols,
                        // foreign-script entries that snuck through filtering, etc.).
                        // The grid renders A-Z cells; anything else can't be placed.
                        // Sort by frequency descending so downstream callers (the CSP solver)
                        // iterate common words first — fewer backtracks when the head matches.
                        val mainWords =
                            parser.records
                                .mapNotNull { record -> toWordWithFreq(record, path) }
                                .sortedByDescending { it.second }
                                .map { it.first }
                        // Merge: for each main word, append the overlay's clue (if
                        // any) to the main word's clue list, preserving the main
                        // clue as primary. This is what makes EST carry both a
                        // verb-form clue (from main, theme=null) and a compass
                        // clue (from themed/compass.csv) at runtime — the filler
                        // picks one at placement time per the per-grid theme caps.
                        // Words in overlays that aren't in the main CSV are added
                        // at the tail (they were curated for theme purposes —
                        // should be available even if the LoRA pipeline didn't
                        // emit them).
                        val byText = HashMap<String, Word>(mainWords.size + overlay.size)
                        for (w in mainWords) {
                            val base = byText[w.text]
                            val themed = overlay[w.text]
                            byText[w.text] =
                                when {
                                    // mainWords is freq-desc; first-seen highest-freq variant wins, else accent-folded homographs clobber it
                                    base != null -> base.copy(clues = base.clues + w.clues)
                                    themed != null ->
                                        Word(
                                            text = w.text,
                                            clues = w.clues + themed.clues,
                                            lemma = w.lemma,
                                        )
                                    else -> w
                                }
                        }
                        for ((text, themedWord) in overlay) {
                            byText.getOrPut(text) { themedWord }
                        }
                        CsvWordRepository(byText.values.toList())
                    }
                }
            }
        }

        /**
         * Reads each `(theme, path)` overlay from the classpath and returns a
         * map keyed by folded-uppercase word text. Each entry's `Word.theme`
         * field is set to the overlay's theme constant. Missing overlay files
         * are tolerated (silently skipped) so a partial deploy doesn't
         * brick the repository.
         */
        private fun loadThemeOverlays(paths: List<Pair<String, String>>): Map<String, Word> {
            if (paths.isEmpty()) return emptyMap()
            val out = HashMap<String, Word>()
            for ((theme, path) in paths) {
                val stream = CsvWordRepository::class.java.getResourceAsStream(path) ?: continue
                stream.use { input ->
                    InputStreamReader(input, StandardCharsets.UTF_8).use { reader ->
                        val format =
                            CSVFormat.RFC4180
                                .builder()
                                .setHeader()
                                .setSkipHeaderRecord(true)
                                .build()
                        CSVParser.parse(reader, format).use { parser ->
                            for (record in parser.records) {
                                val pair = toWordWithFreq(record, path) ?: continue
                                val w = pair.first
                                // Stamp the overlay's theme onto each clue.
                                val themedClues =
                                    w.clues.map {
                                        com.bliss.grid.domain.model
                                            .WordClue(it.text, theme)
                                    }
                                val withTheme =
                                    com.bliss.grid.domain.model.Word(
                                        text = w.text,
                                        clues = themedClues,
                                        lemma = w.lemma,
                                    )
                                // Merge, don't overwrite: a surface in two overlays (e.g. AG in
                                // chem + sigle) must keep BOTH themed clues so pickClue can honour
                                // each theme's cap by the chosen clue.
                                val existing = out[withTheme.text]
                                out[withTheme.text] =
                                    if (existing != null) {
                                        existing.copy(clues = existing.clues + withTheme.clues)
                                    } else {
                                        withTheme
                                    }
                            }
                        }
                    }
                }
            }
            return out
        }

        private fun validateHeader(
            headers: List<String>,
            path: String,
        ) {
            // Accept any of: legacy 8 cols, 8 + lemma, 8 + lemma + theme.
            // Anything else is hand-edited corruption - fail fast.
            val matchesLegacy = headers == REQUIRED_HEADERS
            val matchesWithLemma = headers == REQUIRED_HEADERS + OPTIONAL_LEMMA_HEADER
            val matchesWithTheme =
                headers == REQUIRED_HEADERS + OPTIONAL_LEMMA_HEADER + OPTIONAL_THEME_HEADER
            require(matchesLegacy || matchesWithLemma || matchesWithTheme) {
                "CSV $path header mismatch - expected $REQUIRED_HEADERS " +
                    "(optionally followed by '$OPTIONAL_LEMMA_HEADER', then " +
                    "'$OPTIONAL_THEME_HEADER'), got $headers"
            }
        }

        private fun toWordWithFreq(
            record: CSVRecord,
            path: String,
        ): Pair<Word, Long>? {
            val text = record.get("word")
            require(text.isNotBlank()) { "CSV $path row ${record.recordNumber}: empty word" }
            val frequency = record.get("frequency").toLongOrNull() ?: 0L
            val clue = record.get("clue")
            // Blank clue means "no clue available" — silently drop the row from
            // the usable corpus. The grid generator can't place an unclued
            // word anyway, and forcing the loader to fail would block the
            // entire corpus on any single missing entry.
            if (clue.isBlank()) return null
            // Mots fléchés convention: grid cells are unaccented uppercase ASCII (Word's A-Z
            // invariant in domain). The clue keeps the original accented form for display.
            val folded = foldToAscii(text)
            // Drop entries whose word can't be placed in A-Z cells (rare Unicode that doesn't
            // fold — e.g. ℓ, ß, Greek letters smuggled in via the corpus). Silent skip is fine
            // here: the corpus is large enough that a handful of dropped rows is invisible.
            if (!folded.all { it in 'A'..'Z' }) return null
            // Lemma column is optional (legacy CSVs predate it). When present-and-foldable,
            // store it folded so dedup compares like-with-like; otherwise fall back to the
            // word itself, which makes lemma-dedup degenerate to surface-form dedup.
            val rawLemma = if (OPTIONAL_LEMMA_HEADER in record.parser.headerNames) record.get(OPTIONAL_LEMMA_HEADER) else null
            val foldedLemma =
                rawLemma
                    ?.takeIf { it.isNotBlank() }
                    ?.let(::foldToAscii)
                    ?.takeIf { it.all { ch -> ch in 'A'..'Z' } }
                    ?: folded
            // Theme: read explicit column value if present; otherwise null
            // (= no theme, uncapped). The runtime overlays per-theme curated
            // files at load time (see [loadThemeOverlays]) — those are the
            // source of truth for theme assignment. The CSV's `theme` column
            // is a fallback that lets the corpus carry pre-tagged rows
            // without re-running the overlay pipeline.
            val theme =
                if (OPTIONAL_THEME_HEADER in record.parser.headerNames) {
                    record.get(OPTIONAL_THEME_HEADER).takeIf { it.isNotBlank() }
                } else {
                    null
                }
            return Word(
                text = folded,
                definition = clue,
                lemma = foldedLemma,
                theme = theme,
            ) to frequency
            // Note: the Word(text, definition, lemma, theme) overload wraps
            // (definition, theme) into a single-clue list — the loader's
            // overlay-merge step (in fromClasspath) is what produces the
            // multi-clue case for words that exist in both main + overlay.
        }

        private val DIACRITICS = "\\p{InCombiningDiacriticalMarks}+".toRegex()

        /**
         * Fold to grid-cell ASCII: NFD-normalize, strip combining marks, expand French
         * ligatures (œ→oe, æ→ae — these don't decompose under NFD), uppercase.
         * "Été" → "ETE", "cœur" → "COEUR", "et cætera" → "ET CAETERA".
         */
        private fun foldToAscii(text: String): String =
            DIACRITICS
                .replace(Normalizer.normalize(text, Normalizer.Form.NFD), "")
                .replace("œ", "oe")
                .replace("Œ", "OE")
                .replace("æ", "ae")
                .replace("Æ", "AE")
                .uppercase()
    }
}
