{{/* No Secret here — secrets bootstrapped out-of-band per ADR-0009 §10. */}}
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bliss-billing-api.serviceAccountName" . }}
  labels: {{- include "bliss-billing-api.labels" . | nindent 4 }}
{{- end }}
